export const REMOTE_PROVIDERS = [
  {
    id:          'grok',
    name:        'Grok (xAI)',
    description: 'xAI\'s Grok models - fast, witty, and capable',
    baseUrl:     'https://api.x.ai/v1',
    signupUrl:   'https://x.ai/api',
    signupText:  'Get API key from xAI',
    models:      [
      { id: 'grok-4-1-fast-reasoning', name: 'Grok 4.1 Fast Reasoning', description: '2M context, best for reasoning tasks', pricing: '$0.20/$0.50' },
      { id: 'grok-4-1-fast-non-reasoning', name: 'Grok 4.1 Fast', description: '2M context, fast general purpose', pricing: '$0.20/$0.50' },
      { id: 'grok-code-fast-1', name: 'Grok Code Fast', description: '256K context, optimized for code', pricing: '$0.20/$1.50' },
      { id: 'grok-4-fast-reasoning', name: 'Grok 4 Fast Reasoning', description: '2M context, reasoning tasks', pricing: '$0.20/$0.50' },
      { id: 'grok-4-fast-non-reasoning', name: 'Grok 4 Fast', description: '2M context, fast general purpose', pricing: '$0.20/$0.50' },
      { id: 'grok-4-0709', name: 'Grok 4', description: '256K context, flagship model', pricing: '$3.00/$15.00' },
      { id: 'grok-3-mini', name: 'Grok 3 Mini', description: '131K context, fast and affordable', pricing: '$0.30/$0.50' },
      { id: 'grok-3', name: 'Grok 3', description: '131K context, previous flagship', pricing: '$3.00/$15.00' },
    ],
  },
  {
    id:          'openai',
    name:        'OpenAI',
    description: 'GPT-4, GPT-3.5, and other OpenAI models',
    baseUrl:     'https://api.openai.com/v1',
    signupUrl:   'https://platform.openai.com/signup',
    signupText:  'Get API key from OpenAI',
    models:      [
      { id: 'gpt-4o', name: 'GPT-4o', description: 'Most capable multimodal model' },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini', description: 'Fast and affordable' },
      { id: 'gpt-4-turbo', name: 'GPT-4 Turbo', description: 'High capability with vision' },
    ],
  },
  {
    id:          'anthropic',
    name:        'Anthropic',
    description: 'Claude models - safe, helpful, and honest',
    baseUrl:     'https://api.anthropic.com/v1',
    signupUrl:   'https://console.anthropic.com/',
    signupText:  'Get API key from Anthropic',
    models:      [
      { id: 'claude-3-5-sonnet-20241022', name: 'Claude 3.5 Sonnet', description: 'Best balance of speed and capability' },
      { id: 'claude-3-opus-20240229', name: 'Claude 3 Opus', description: 'Most capable Claude model' },
      { id: 'claude-3-haiku-20240307', name: 'Claude 3 Haiku', description: 'Fastest Claude model' },
    ],
  },
  {
    id:          'google',
    name:        'Google AI',
    description: 'Gemini models from Google',
    baseUrl:     'https://generativelanguage.googleapis.com/v1beta',
    signupUrl:   'https://ai.google.dev/',
    signupText:  'Get API key from Google AI',
    models:      [
      { id: 'gemini-1.5-pro', name: 'Gemini 1.5 Pro', description: 'Most capable Gemini model' },
      { id: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash', description: 'Fast and efficient' },
    ],
  },
  {
    id:          'kimi',
    name:        'Kimi (Moonshot AI)',
    description: 'Kimi K2.5 models from Moonshot AI',
    baseUrl:     'https://api.moonshot.cn/v1',
    signupUrl:   'https://platform.moonshot.cn/',
    signupText:  'Get API key from Moonshot AI',
    models:      [
      { id: 'kimi-k2.5', name: 'Kimi K2.5', description: '256K context, advanced reasoning and long-context capabilities' },
      { id: 'kimi-k2', name: 'Kimi K2', description: '200K context, balanced performance' },
    ],
  },
  {
    id:          'nvidia',
    name:        'NVIDIA (Free Moonshot/Kimi)',
    description: 'Access Moonshot Kimi models for free through NVIDIA API',
    baseUrl:     'https://integrate.api.nvidia.com/v1',
    signupUrl:   'https://build.nvidia.com/',
    signupText:  'Get free API key from NVIDIA (includes Moonshot access)',
    models:      [
      { id: 'moonshotai/kimi-k2.5', name: 'Kimi K2.5 (Free)', description: '256K context, FREE through NVIDIA API' },
      { id: 'moonshotai/kimi-k2', name: 'Kimi K2 (Free)', description: '200K context, FREE through NVIDIA API' },
      { id: 'nvidia/llama-3.1-nemotron-70b-instruct', name: 'Llama 3.1 Nemotron 70B', description: 'NVIDIA optimized Llama model' },
      { id: 'meta/llama-3.1-70b-instruct', name: 'Llama 3.1 70B', description: 'Meta Llama 3.1' },
    ],
  },
  {
    id:          'alibaba',
    name:        'Alibaba Cloud (DashScope)',
    description: 'Access MiniMax, Kimi K2.5, Qwen, and other models via Alibaba Cloud Model Studio',
    baseUrl:     'https://coding-intl.dashscope.aliyuncs.com/v1',
    signupUrl:   'https://bailian.console.alibabacloud.com/',
    signupText:  'Get API key from Alibaba Cloud Model Studio',
    models:      [
      { id: 'qwen3.5-plus', name: 'Qwen 3.5 Plus', description: 'Latest Qwen, balanced performance' },
      { id: 'MiniMax-M2.5', name: 'MiniMax M2.5', description: '200K context, advanced reasoning' },
      { id: 'kimi-k2.5', name: 'Kimi K2.5', description: '256K context, long-context reasoning' },
      { id: 'glm-5', name: 'GLM 5', description: 'Zhipu GLM flagship model' },
      { id: 'qwen3-coder-plus', name: 'Qwen 3 Coder Plus', description: 'Optimized for code generation' },
      { id: 'qwen3-coder-next', name: 'Qwen 3 Coder Next', description: 'Next-gen code model' },
      { id: 'qwen3-max-2026-01-23', name: 'Qwen 3 Max', description: 'Most capable Qwen 3 model' },
      { id: 'glm-4.7', name: 'GLM 4.7', description: 'Zhipu GLM 4.7' },
    ],
  },
  {
    id:          'cohere',
    name:        'Cohere',
    description: 'Command A, Command R, Command R+, and Command R7B models - support tool use - 1,000 API calls/month free tier',
    baseUrl:     'https://api.cohere.ai/compatibility/v1',
    signupUrl:   'https://dashboard.cohere.com/api-keys',
    signupText:  'Get free API key from Cohere',
    models:      [
      // Command A - Latest flagship (supports tool use)
      { id: 'command-a-03-2025', name: 'Command A', description: 'Latest flagship - tool use, RAG, agents' },
      { id: 'command-a-reasoning-08-2025', name: 'Command A Reasoning', description: 'Advanced reasoning - tool use, complex reasoning' },
      { id: 'command-a-translate-08-2025', name: 'Command A Translate', description: 'Translation optimized - tool use, multilingual' },
      { id: 'command-a-vision-07-2025', name: 'Command A Vision', description: 'Multimodal vision - tool use, image + text' },
      // Command R7B - Fast lightweight (supports tool use)
      { id: 'command-r7b-12-2024', name: 'Command R7B', description: 'Fast, lightweight - tool use, RAG, everyday tasks' },
      { id: 'command-r7b-arabic-02-2025', name: 'Command R7B Arabic', description: 'Arabic optimized - tool use, fast, lightweight' },
      // Command R - Balanced (supports tool use)
      { id: 'command-r-08-2024', name: 'Command R (08-2024)', description: 'Balanced - tool use, conversation, RAG' },
      { id: 'command-r-03-2024', name: 'Command R (03-2024)', description: 'Earlier Command R - tool use, conversation' },
      { id: 'command-r', name: 'Command R', description: 'Balanced - tool use, everyday tasks' },
      // Command R+ - Advanced reasoning (supports tool use)
      { id: 'command-r-plus-08-2024', name: 'Command R+ (08-2024)', description: 'Advanced reasoning - tool use, complex tasks' },
      { id: 'command-r-plus-04-2024', name: 'Command R+ (04-2024)', description: 'Earlier Command R+ - tool use, reasoning' },
      { id: 'command-r-plus', name: 'Command R+', description: 'Advanced reasoning - tool use, complex tasks' },
    ],
  },
  {
    id:          'deepseek',
    name:        'DeepSeek',
    description: 'DeepSeek V4 Flash and V4 Pro models - all support tool use - 500M tokens/day free tier',
    baseUrl:     'https://api.deepseek.com',
    signupUrl:   'https://platform.deepseek.com',
    signupText:  'Get free API key from DeepSeek',
    models:      [
      { id: 'deepseek-v4-flash', name: 'DeepSeek V4 Flash', description: 'Fast, efficient model - tool use, coding, reasoning (non-thinking mode)' },
      { id: 'deepseek-v4-pro', name: 'DeepSeek V4 Pro', description: 'Most capable model - tool use, complex reasoning, coding' },
      // Legacy aliases (to be deprecated 2026/07/24)
      { id: 'deepseek-chat', name: 'DeepSeek-Chat (Legacy)', description: 'TO BE DEPRECATED 2026/07/24 - Maps to V4 Flash non-thinking mode' },
      { id: 'deepseek-reasoner', name: 'DeepSeek-R1 Reasoner (Legacy)', description: 'TO BE DEPRECATED 2026/07/24 - Maps to V4 Flash thinking mode' },
    ],
  },
];
