import type { ToolManifest } from '../registry';

export const githubToolManifests: ToolManifest[] = [
  {
    name:        'github_add_remote',
    description: 'Add a remote repository to an existing git repository.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository' },
      remoteName:   { type: 'string', description: "Name of the remote (usually 'origin')" },
      remoteUrl:    { type: 'string', description: 'URL of the remote repository' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_add_remote'),
  },
  {
    name:        'github_comment_on_issue',
    description: 'Add a comment to a GitHub issue.',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Repository owner (username or organization)' },
      repo:         { type: 'string', description: 'Repository name' },
      issue_number: { type: 'number', description: 'Issue number' },
      body:         { type: 'string', description: 'Comment body' },
    },
    operationTypes: ['execute', 'create'],
    loader:         () => import('./github_comment_on_issue'),
  },
  {
    name:        'github_create_file',
    description: 'Create a new file in a GitHub repository.',
    category:    'github',
    schemaDef:   {
      owner:   { type: 'string', description: 'Repository owner (username or organization)' },
      repo:    { type: 'string', description: 'Repository name' },
      path:    { type: 'string', description: 'Path where the file should be created' },
      content: { type: 'string', description: 'Content of the file' },
      message: { type: 'string', description: 'Commit message' },
      branch:  { type: 'string', optional: true, description: 'Branch to create the file on' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_create_file'),
  },
  {
    name:        'github_get_issue',
    description: 'Get details of a specific GitHub issue.',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Repository owner (username or organization)' },
      repo:         { type: 'string', description: 'Repository name' },
      issue_number: { type: 'number', description: 'Issue number' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_get_issue'),
  },
  {
    name:        'github_get_issue_comments',
    description: 'Read the comment thread on a GitHub issue or pull request (PRs are issues in the API — pass the PR number). Returns each comment with author, association, timestamp, and body.',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Repository owner (username or organization)' },
      repo:         { type: 'string', description: 'Repository name' },
      issue_number: { type: 'number', description: 'Issue or PR number' },
      limit:        { type: 'number', optional: true, default: 30, description: 'Max comments to return (fetched newest-paginated, capped to this)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_get_issue_comments'),
  },
  {
    name:        'github_get_issues',
    description: 'Get issues from a GitHub repository.',
    category:    'github',
    schemaDef:   {
      owner:  { type: 'string', description: 'Repository owner (username or organization)' },
      repo:   { type: 'string', description: 'Repository name' },
      state:  { type: 'enum', enum: ['open', 'closed', 'all'], default: 'open', description: 'Issue state filter' },
      labels: { type: 'array', items: { type: 'string' }, optional: true, description: 'Labels to filter issues' },
      since:  { type: 'string', optional: true, description: 'Only issues updated after this ISO 8601 timestamp' },
      limit:  { type: 'number', optional: true, default: 10, description: 'Maximum number of issues to return' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_get_issues'),
  },
  {
    name:        'github_init',
    description: 'Initialize a git repository at the specified absolute path.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path where the git repository should be initialized' },
    },
    operationTypes: ['execute', 'create'],
    loader:         () => import('./github_init'),
  },
  {
    name:        'github_list_branches',
    description: 'List branches in a GitHub repository.',
    category:    'github',
    schemaDef:   {
      owner:     { type: 'string', description: 'Repository owner (username or organization)' },
      repo:      { type: 'string', description: 'Repository name' },
      protected: { type: 'boolean', optional: true, description: 'Filter for protected branches only' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_list_branches'),
  },
  {
    name:        'github_read_file',
    description: 'Read the contents of a file from a GitHub repository.',
    category:    'github',
    schemaDef:   {
      owner: { type: 'string', description: 'Repository owner (username or organization)' },
      repo:  { type: 'string', description: 'Repository name' },
      path:  { type: 'string', description: 'Path to the file in the repository' },
      ref:   { type: 'string', optional: true, description: 'Branch, tag, or commit SHA' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_read_file'),
  },
  {
    name:        'github_update_file',
    description: 'Update an existing file in a GitHub repository. Automatically fetches the current file SHA required for updates.',
    category:    'github',
    schemaDef:   {
      owner:   { type: 'string', description: 'Repository owner (username or organization)' },
      repo:    { type: 'string', description: 'Repository name' },
      path:    { type: 'string', description: 'Path to the file to update' },
      content: { type: 'string', description: 'New content of the file' },
      message: { type: 'string', description: 'Commit message' },
      branch:  { type: 'string', optional: true, description: 'Branch to update the file on' },
    },
    operationTypes: ['update'],
    loader:         () => import('./github_update_file'),
  },
  {
    name:        'git_blame',
    description: 'Show who last modified each line of a file. Optionally limit to a line range.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the file to blame' },
      startLine:    { type: 'number', optional: true, description: 'Start line number (1-indexed)' },
      endLine:      { type: 'number', optional: true, description: 'End line number (1-indexed)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./git_blame'),
  },
  {
    name:        'git_pull',
    description: 'Pull commits from a remote repository. Automatically reports any merge conflicts after pull.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      remote:       { type: 'string', optional: true, description: "Remote name (defaults to 'origin')" },
      branch:       { type: 'string', optional: true, description: 'Branch to pull (defaults to current branch)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./git_pull'),
  },
  {
    name:        'git_conflicts',
    description: 'List files with merge conflicts and show the conflict diffs for each file.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./git_conflicts'),
  },
  {
    name:        'git_add',
    description: 'Stage files for commit. If no files are specified, stages all changes.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      files:        { type: 'array', items: { type: 'string' }, optional: true, description: 'Absolute file paths to stage. If omitted, stages all changes.' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./git_add'),
  },
  {
    name:        'git_commit',
    description: 'Stage files and create a git commit. If no files are specified, stages all changes.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      message:      { type: 'string', description: 'Commit message' },
      files:        { type: 'array', items: { type: 'string' }, optional: true, description: 'Absolute file paths to stage. If omitted, stages all changes.' },
    },
    operationTypes: ['execute', 'create'],
    loader:         () => import('./git_commit'),
  },
  {
    name:        'git_push',
    description: 'Push commits to a remote repository.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      remote:       { type: 'string', optional: true, description: "Remote name (defaults to 'origin')" },
      branch:       { type: 'string', optional: true, description: 'Branch to push (defaults to current branch)' },
      tags:         { type: 'boolean', optional: true, description: 'Push all local tags instead of a branch (git push --tags)' },
      force:        { type: 'boolean', optional: true, description: 'Force push using --force-with-lease (use after rebase)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./git_push'),
  },
  {
    name:        'git_worktree',
    description: 'Add, list, remove, or prune git worktrees — check out multiple branches of one repo into separate directories at once (ideal for reviewing/building several PRs in parallel).',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      action:       { type: 'enum', enum: ['add', 'list', 'remove', 'prune'], description: 'Worktree operation to perform' },
      worktreePath: { type: 'string', optional: true, description: 'Absolute path for the worktree directory (required for add/remove)' },
      branch:       { type: 'string', optional: true, description: 'Branch (or commit-ish) to check out in the new worktree (add). With createBranch=true, the new branch name to create.' },
      createBranch: { type: 'boolean', optional: true, description: 'If true, create a NEW branch named `branch` in the added worktree (git worktree add -b)' },
      commitish:    { type: 'string', optional: true, description: 'Base commit/ref for the new branch or detached worktree (add)' },
      force:        { type: 'boolean', optional: true, description: 'Force removal even if the worktree has changes (remove)' },
    },
    operationTypes: ['execute', 'create'],
    loader:         () => import('./git_worktree'),
  },
  {
    name:        'github_create_issue',
    description: 'Create a new issue in a GitHub repository.',
    category:    'github',
    schemaDef:   {
      owner:     { type: 'string', description: 'Repository owner (username or organization)' },
      repo:      { type: 'string', description: 'Repository name' },
      title:     { type: 'string', description: 'Issue title' },
      body:      { type: 'string', optional: true, description: 'Issue body/description (markdown supported)' },
      labels:    { type: 'array', items: { type: 'string' }, optional: true, description: 'Labels to apply to the issue' },
      assignees: { type: 'array', items: { type: 'string' }, optional: true, description: 'GitHub usernames to assign' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_create_issue'),
  },
  {
    name:        'github_update_issue',
    description: 'Update an existing GitHub issue — edit title, body, labels, assignees, or state.',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Repository owner (username or organization)' },
      repo:         { type: 'string', description: 'Repository name' },
      issue_number: { type: 'number', description: 'Issue number' },
      title:        { type: 'string', optional: true, description: 'New title' },
      body:         { type: 'string', optional: true, description: 'New body' },
      state:        { type: 'enum', enum: ['open', 'closed'], optional: true, description: 'Set issue state' },
      labels:       { type: 'array', items: { type: 'string' }, optional: true, description: 'Replace labels' },
      assignees:    { type: 'array', items: { type: 'string' }, optional: true, description: 'Replace assignees' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./github_update_issue'),
  },
  {
    name:        'github_close_issue',
    description: 'Close a GitHub issue with an optional reason (completed or not_planned).',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Repository owner (username or organization)' },
      repo:         { type: 'string', description: 'Repository name' },
      issue_number: { type: 'number', description: 'Issue number' },
      reason:       { type: 'enum', enum: ['completed', 'not_planned'], optional: true, description: "Close reason (defaults to 'completed')" },
    },
    operationTypes: ['execute'],
    loader:         () => import('./github_close_issue'),
  },
  {
    name:        'github_create_pr',
    description: 'Create a pull request in a GitHub repository.',
    category:    'github',
    schemaDef:   {
      owner: { type: 'string', description: 'Repository owner (username or organization)' },
      repo:  { type: 'string', description: 'Repository name' },
      title: { type: 'string', description: 'Pull request title' },
      head:  { type: 'string', description: 'Branch containing your changes' },
      base:  { type: 'string', optional: true, description: "Branch to merge into (defaults to 'main')" },
      body:  { type: 'string', optional: true, description: 'Pull request description (markdown supported)' },
      draft: { type: 'boolean', optional: true, description: 'Create as a draft PR' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_create_pr'),
  },
  {
    name:        'github_ready_pr',
    description: 'Flip a draft pull request to "ready for review" (draft PRs cannot be merged). Uses the GraphQL markPullRequestReadyForReview mutation.',
    category:    'github',
    schemaDef:   {
      owner:       { type: 'string', description: 'Repository owner (username or organization)' },
      repo:        { type: 'string', description: 'Repository name' },
      pull_number: { type: 'number', description: 'Pull request number' },
    },
    operationTypes: ['update'],
    loader:         () => import('./github_ready_pr'),
  },
  {
    name:        'github_merge_pr',
    description: 'Merge a GitHub pull request. Destructive — refuses without {"confirm":true}. Supports merge, squash, and rebase methods.',
    category:    'github',
    schemaDef:   {
      owner:          { type: 'string', description: 'Repository owner.' },
      repo:           { type: 'string', description: 'Repository name.' },
      pull_number:    { type: 'number', description: 'PR number to merge.' },
      merge_method:   { type: 'string', optional: true, description: 'merge | squash | rebase (default "merge").' },
      commit_title:   { type: 'string', optional: true, description: 'Override commit title (squash and merge methods only).' },
      commit_message: { type: 'string', optional: true, description: 'Override commit body.' },
      confirm:        { type: 'boolean', description: 'Must be true to actually merge.' },
    },
    operationTypes: ['update'],
    loader:         () => import('./github_merge_pr'),
  },
  {
    name:        'github_create_release',
    description: 'Cut a GitHub release (and its git tag). Publishing a non-draft release is outward-facing — refuses without {"confirm":true}; use {"draft":true} for a safe draft. Supports auto-generated release notes.',
    category:    'github',
    schemaDef:   {
      owner:                  { type: 'string', description: 'Repository owner.' },
      repo:                   { type: 'string', description: 'Repository name.' },
      tag_name:               { type: 'string', description: 'Git tag for the release (created if it does not exist).' },
      target_commitish:       { type: 'string', optional: true, description: 'Branch or SHA the tag is created from (defaults to the repo default branch).' },
      name:                   { type: 'string', optional: true, description: 'Release title (defaults to the tag).' },
      body:                   { type: 'string', optional: true, description: 'Release notes (markdown).' },
      draft:                  { type: 'boolean', optional: true, description: 'Create as a draft (not published). No confirm needed.' },
      prerelease:             { type: 'boolean', optional: true, description: 'Mark as a prerelease.' },
      generate_release_notes: { type: 'boolean', optional: true, description: 'Auto-generate notes from merged PRs since the previous tag.' },
      confirm:                { type: 'boolean', optional: true, description: 'Must be true to publish a non-draft release.' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_create_release'),
  },
  {
    name:        'github_check_runs',
    description: 'List CI check runs for a ref (branch name, SHA, or tag). Use this to answer "is CI green?" — shows status / conclusion / timing for each check.',
    category:    'github',
    schemaDef:   {
      owner: { type: 'string', description: 'Repository owner.' },
      repo:  { type: 'string', description: 'Repository name.' },
      ref:   { type: 'string', description: 'Branch name, SHA, or tag to check.' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_check_runs'),
  },
  {
    name:        'github_trigger_workflow_run',
    description: 'Manually trigger a GitHub Actions workflow via workflow_dispatch. The target workflow must declare a workflow_dispatch trigger in its "on:" block.',
    category:    'github',
    schemaDef:   {
      owner:       { type: 'string', description: 'Repository owner.' },
      repo:        { type: 'string', description: 'Repository name.' },
      workflow_id: { type: 'string', description: 'Workflow filename (e.g. "ci.yml") or numeric id.' },
      ref:         { type: 'string', optional: true, description: 'Branch/tag/SHA to run on (default "main").' },
      inputs:      { type: 'object', optional: true, description: 'Input values declared in the workflow dispatch spec.' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./github_trigger_workflow_run'),
  },
  {
    name:        'git_branch',
    description: 'Create, switch, delete, or list git branches.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      action:       { type: 'enum', enum: ['list', 'create', 'switch', 'delete'], description: 'Branch action to perform' },
      branchName:   { type: 'string', optional: true, description: 'Branch name (required for create, switch, delete)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./git_branch'),
  },
  {
    name:        'git_status',
    description: 'Show the working tree status — current branch, staged/unstaged/untracked files.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./git_status'),
  },
  {
    name:        'git_log',
    description: 'Show commit history for a repository.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      limit:        { type: 'number', optional: true, description: 'Number of commits to show (defaults to 20)' },
      oneline:      { type: 'boolean', optional: true, description: 'One-line format (defaults to true)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./git_log'),
  },
  {
    name:        'git_diff',
    description: 'Show changes between working tree, staging area, or commits.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      staged:       { type: 'boolean', optional: true, description: 'Show staged (cached) changes only' },
      commitA:      { type: 'string', optional: true, description: 'First commit SHA for comparison' },
      commitB:      { type: 'string', optional: true, description: 'Second commit SHA for comparison' },
      filePath:     { type: 'string', optional: true, description: 'Limit diff to a specific file path' },
    },
    operationTypes: ['read'],
    loader:         () => import('./git_diff'),
  },
  {
    name:        'git_stash',
    description: 'Save, list, apply, pop, or drop stashed changes.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      action:       { type: 'enum', enum: ['save', 'list', 'apply', 'pop', 'drop'], description: 'Stash action to perform' },
      message:      { type: 'string', optional: true, description: 'Stash message (for save action)' },
      stashRef:     { type: 'string', optional: true, description: "Stash reference like 'stash@{0}' (for apply/pop/drop, defaults to stash@{0})" },
    },
    operationTypes: ['execute'],
    loader:         () => import('./git_stash'),
  },
  {
    name:        'git_checkout',
    description: 'Restore files from a commit or branch, or discard working tree changes.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      files:        { type: 'array', items: { type: 'string' }, description: 'Absolute file paths to restore' },
      ref:          { type: 'string', optional: true, description: 'Commit SHA or branch to restore from (defaults to HEAD)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./git_checkout'),
  },
];
