import type { ToolManifest } from '../registry';

export const githubToolManifests: ToolManifest[] = [
  {
    name:        'github_add_remote',
    description: 'Add a remote repository to an existing git repository.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository' },
      remoteName:   { type: 'string', description: "Name of the remote (usually 'origin')" },
      remoteUrl:    { type: 'string', description: 'URL of the remote repository' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_add_remote'),
  },
  {
    name:        'github_comment_on_issue',
    description: 'Add a comment to a GitHub issue.',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Repository owner (username or organization)' },
      repo:         { type: 'string', description: 'Repository name' },
      issue_number: { type: 'number', description: 'Issue number' },
      body:         { type: 'string', description: 'Comment body' },
    },
    operationTypes: ['execute', 'create'],
    loader:         () => import('./github_comment_on_issue'),
  },
  {
    name:        'github_create_file',
    description: 'Create a new file in a GitHub repository.',
    category:    'github',
    schemaDef:   {
      owner:   { type: 'string', description: 'Repository owner (username or organization)' },
      repo:    { type: 'string', description: 'Repository name' },
      path:    { type: 'string', description: 'Path where the file should be created' },
      content: { type: 'string', description: 'Content of the file' },
      message: { type: 'string', description: 'Commit message' },
      branch:  { type: 'string', optional: true, description: 'Branch to create the file on' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_create_file'),
  },
  {
    name:        'github_get_issue',
    description: 'Get details of a specific GitHub issue.',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Repository owner (username or organization)' },
      repo:         { type: 'string', description: 'Repository name' },
      issue_number: { type: 'number', description: 'Issue number' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_get_issue'),
  },
  {
    name:        'github_get_issue_comments',
    description: 'Read the comment thread on a GitHub issue or pull request (PRs are issues in the API — pass the PR number). Returns each comment with author, association, timestamp, and body.',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Repository owner (username or organization)' },
      repo:         { type: 'string', description: 'Repository name' },
      issue_number: { type: 'number', description: 'Issue or PR number' },
      limit:        { type: 'number', optional: true, default: 30, description: 'Max comments to return (fetched newest-paginated, capped to this)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_get_issue_comments'),
  },
  {
    name:        'github_get_issues',
    description: 'Get issues from a GitHub repository.',
    category:    'github',
    schemaDef:   {
      owner:  { type: 'string', description: 'Repository owner (username or organization)' },
      repo:   { type: 'string', description: 'Repository name' },
      state:  { type: 'enum', enum: ['open', 'closed', 'all'], default: 'open', description: 'Issue state filter' },
      labels: { type: 'array', items: { type: 'string' }, optional: true, description: 'Labels to filter issues' },
      since:  { type: 'string', optional: true, description: 'Only issues updated after this ISO 8601 timestamp' },
      limit:  { type: 'number', optional: true, default: 10, description: 'Maximum number of issues to return' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_get_issues'),
  },
  {
    name:        'heartbeat_new_issues',
    description: 'Heartbeat issue-discovery (#500) "touched-before" filter: given the open-issue union from scan_active_issues, returns only issues Heartbeat has NOT handled before — anti-joined against the heartbeat_seen_issues seen-set and excluding issues already assigned to Heartbeat or bearing the claim label. Deterministic, zero-LLM, read-only. Call before triaging so the same issue is never picked up twice.',
    category:    'github',
    schemaDef:   {
      issues:         { type: 'array', items: { type: 'object' }, description: 'The open-issue array from scan_active_issues. Each item: { owner, repo, number|issue_number, node_id?, title?, assignees?, labels? }.' },
      heartbeat_login: { type: 'string', optional: true, description: 'GitHub login Heartbeat self-assigns as. Issues already assigned to it are excluded as already-claimed.' },
      claim_label:    { type: 'string', optional: true, description: "Label used to stake a claim (default 'heartbeat'). Issues already bearing it are excluded." },
    },
    operationTypes: ['read'],
    loader:         () => import('./heartbeat_new_issues'),
  },
  {
    name:        'heartbeat_claim_issue',
    description: 'Heartbeat issue-discovery (#500) atomic claim + collision guard: records an issue in the heartbeat_seen_issues seen-set via INSERT ... ON CONFLICT DO NOTHING. Returns won=true if THIS call staked the claim (proceed to self-assign on GitHub + triage) or won=false if another cycle/agent already claimed it (back off). Call this FIRST, before any GitHub-side self-assign, so two agents cannot both pick up the same issue.',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Repository owner (username or organization)' },
      repo:         { type: 'string', description: 'Repository name' },
      issue_number: { type: 'number', description: 'Issue number to claim' },
      node_id:      { type: 'string', optional: true, description: 'GitHub GraphQL node id of the issue (for audit).' },
      title:        { type: 'string', optional: true, description: 'Issue title (for audit/readability).' },
      claim_method: { type: 'string', optional: true, description: "How the claim is staked on GitHub: 'assign' | 'label' | 'comment' | 'preexisting' | 'seen' (default 'seen')." },
    },
    operationTypes: ['create', 'execute'],
    loader:         () => import('./heartbeat_claim_issue'),
  },
  {
    name:        'github_list_projects',
    description: 'List Projects V2 boards for an org or user, with each board\'s node id (projectId, PVT_…), fields, and — for single-select fields like Status — every option id/name. Projects V2 is GraphQL-only (no REST). This is the orientation step: you need the projectId + fieldId + optionId before adding cards or moving them between columns. Returns open boards only.',
    category:    'github',
    schemaDef:   {
      owner:      { type: 'string', description: 'Org or user login that owns the boards.' },
      owner_type: { type: 'string', optional: true, description: "'organization' | 'user' | 'auto' (default 'auto' — tries org then falls back to user)." },
      limit:      { type: 'number', optional: true, description: 'Max boards to return (default 20, capped at 50).' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_list_projects'),
  },
  {
    name:        'github_add_issue_to_project',
    description: 'Add an issue (or PR) as a card on a Projects V2 board via addProjectV2ItemById (GraphQL-only). Address the board by project_id (PVT_… from github_list_projects) and the issue by content_node_id, or supply owner + repo + issue_number to resolve it. Idempotent — an issue already on the board returns its existing item id. Returns the itemId (PVTI_…) needed by github_set_project_field.',
    category:    'github',
    schemaDef:   {
      project_id:      { type: 'string', description: 'Board node id (PVT_…) from github_list_projects.' },
      content_node_id: { type: 'string', optional: true, description: 'GraphQL node id of the issue/PR. If omitted, resolved from owner+repo+issue_number.' },
      owner:           { type: 'string', optional: true, description: 'Repository owner (used only when content_node_id is omitted).' },
      repo:            { type: 'string', optional: true, description: 'Repository name (used only when content_node_id is omitted).' },
      issue_number:    { type: 'number', optional: true, description: 'Issue number (used only when content_node_id is omitted).' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_add_issue_to_project'),
  },
  {
    name:        'github_set_project_field',
    description: 'Set one field on one Projects V2 card via updateProjectV2ItemFieldValue (GraphQL-only) — most often the Status single-select, i.e. moving a card between columns. All ids come from the prior steps: project_id + field_id (+ option_id) from github_list_projects, item_id from github_add_issue_to_project. Provide exactly one value: option_id (single-select), text, number, or date.',
    category:    'github',
    schemaDef:   {
      project_id: { type: 'string', description: 'Board node id (PVT_…).' },
      item_id:    { type: 'string', description: 'Card item id (PVTI_…) from github_add_issue_to_project.' },
      field_id:   { type: 'string', description: 'Field node id from github_list_projects.' },
      option_id:  { type: 'string', optional: true, description: 'Single-select option id (from github_list_projects). Use for Status/column fields.' },
      text:       { type: 'string', optional: true, description: 'Text value (for text fields).' },
      number:     { type: 'number', optional: true, description: 'Number value (for number fields).' },
      date:       { type: 'string', optional: true, description: 'Date value YYYY-MM-DD (for date fields).' },
    },
    operationTypes: ['update'],
    loader:         () => import('./github_set_project_field'),
  },
  {
    name:        'github_init',
    description: 'Initialize a git repository at the specified absolute path.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path where the git repository should be initialized' },
    },
    operationTypes: ['execute', 'create'],
    loader:         () => import('./github_init'),
  },
  {
    name:        'github_list_branches',
    description: 'List branches in a GitHub repository.',
    category:    'github',
    schemaDef:   {
      owner:     { type: 'string', description: 'Repository owner (username or organization)' },
      repo:      { type: 'string', description: 'Repository name' },
      protected: { type: 'boolean', optional: true, description: 'Filter for protected branches only' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_list_branches'),
  },
  {
    name:        'github_create_ref',
    description: 'Create a remote branch (or tag) on GitHub, pointed at an explicit SHA or the current tip of another branch (from_branch). Completes remote-branch lifecycle with github_list_branches / github_delete_ref.',
    category:    'github',
    schemaDef:   {
      owner:       { type: 'string', description: 'Repository owner (username or organization)' },
      repo:        { type: 'string', description: 'Repository name' },
      branch:      { type: 'string', description: 'New branch (or tag) name to create, e.g. "feature/x"' },
      sha:         { type: 'string', optional: true, description: 'Commit SHA the new ref points at (required unless from_branch is given)' },
      from_branch: { type: 'string', optional: true, description: 'Existing branch whose current tip SHA the new ref should point at' },
      ref_type:    { type: 'enum', enum: ['heads', 'tags'], optional: true, default: 'heads', description: 'Create a branch (heads, default) or a tag (tags)' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_create_ref'),
  },
  {
    name:        'github_delete_ref',
    description: 'Delete a remote branch (or tag) on GitHub. Destructive + outward-facing — refuses without {"confirm":true}; reports the deleted SHA so it can be restored via github_create_ref.',
    category:    'github',
    schemaDef:   {
      owner:    { type: 'string', description: 'Repository owner (username or organization)' },
      repo:     { type: 'string', description: 'Repository name' },
      branch:   { type: 'string', description: 'Branch (or tag) name to delete, e.g. "feature/x" (accepts "heads/x" / "refs/heads/x" too)' },
      ref_type: { type: 'enum', enum: ['heads', 'tags'], optional: true, default: 'heads', description: 'Delete a branch (heads, default) or a tag (tags)' },
      confirm:  { type: 'boolean', optional: true, description: 'Must be true to actually delete (destructive).' },
    },
    operationTypes: ['delete'],
    loader:         () => import('./github_delete_ref'),
  },
  {
    name:        'github_read_file',
    description: 'Read the contents of a file from a GitHub repository.',
    category:    'github',
    schemaDef:   {
      owner: { type: 'string', description: 'Repository owner (username or organization)' },
      repo:  { type: 'string', description: 'Repository name' },
      path:  { type: 'string', description: 'Path to the file in the repository' },
      ref:   { type: 'string', optional: true, description: 'Branch, tag, or commit SHA' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_read_file'),
  },
  {
    name:        'github_update_file',
    description: 'Update an existing file in a GitHub repository. Automatically fetches the current file SHA required for updates.',
    category:    'github',
    schemaDef:   {
      owner:   { type: 'string', description: 'Repository owner (username or organization)' },
      repo:    { type: 'string', description: 'Repository name' },
      path:    { type: 'string', description: 'Path to the file to update' },
      content: { type: 'string', description: 'New content of the file' },
      message: { type: 'string', description: 'Commit message' },
      branch:  { type: 'string', optional: true, description: 'Branch to update the file on' },
    },
    operationTypes: ['update'],
    loader:         () => import('./github_update_file'),
  },
  {
    name:        'git_blame',
    description: 'Show who last modified each line of a file. Optionally limit to a line range.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the file to blame' },
      startLine:    { type: 'number', optional: true, description: 'Start line number (1-indexed)' },
      endLine:      { type: 'number', optional: true, description: 'End line number (1-indexed)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./git_blame'),
  },
  {
    name:        'git_pull',
    description: 'Pull commits from a remote repository. Automatically reports any merge conflicts after pull.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      remote:       { type: 'string', optional: true, description: "Remote name (defaults to 'origin')" },
      branch:       { type: 'string', optional: true, description: 'Branch to pull (defaults to current branch)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./git_pull'),
  },
  {
    name:        'git_conflicts',
    description: 'List files with merge conflicts and show the conflict diffs for each file.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./git_conflicts'),
  },
  {
    name:        'git_add',
    description: 'Stage files for commit. If no files are specified, stages all changes.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      files:        { type: 'array', items: { type: 'string' }, optional: true, description: 'Absolute file paths to stage. If omitted, stages all changes.' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./git_add'),
  },
  {
    name:        'git_commit',
    description: 'Stage files and create a git commit. If no files are specified, stages all changes.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      message:      { type: 'string', description: 'Commit message' },
      files:        { type: 'array', items: { type: 'string' }, optional: true, description: 'Absolute file paths to stage. If omitted, stages all changes.' },
    },
    operationTypes: ['execute', 'create'],
    loader:         () => import('./git_commit'),
  },
  {
    name:        'git_push',
    description: 'Push commits to a remote repository.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      remote:       { type: 'string', optional: true, description: "Remote name (defaults to 'origin')" },
      branch:       { type: 'string', optional: true, description: 'Branch to push (defaults to current branch)' },
      tags:         { type: 'boolean', optional: true, description: 'Push all local tags instead of a branch (git push --tags)' },
      force:        { type: 'boolean', optional: true, description: 'Force push using --force-with-lease (use after rebase)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./git_push'),
  },
  {
    name:        'git_worktree',
    description: 'Add, list, remove, or prune git worktrees — check out multiple branches of one repo into separate directories at once (ideal for reviewing/building several PRs in parallel).',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      action:       { type: 'enum', enum: ['add', 'list', 'remove', 'prune'], description: 'Worktree operation to perform' },
      worktreePath: { type: 'string', optional: true, description: 'Absolute path for the worktree directory (required for add/remove)' },
      branch:       { type: 'string', optional: true, description: 'Branch (or commit-ish) to check out in the new worktree (add). With createBranch=true, the new branch name to create.' },
      createBranch: { type: 'boolean', optional: true, description: 'If true, create a NEW branch named `branch` in the added worktree (git worktree add -b)' },
      commitish:    { type: 'string', optional: true, description: 'Base commit/ref for the new branch or detached worktree (add)' },
      force:        { type: 'boolean', optional: true, description: 'Force removal even if the worktree has changes (remove)' },
    },
    operationTypes: ['execute', 'create'],
    loader:         () => import('./git_worktree'),
  },
  {
    name:        'github_create_issue',
    description: 'Create a new issue in a GitHub repository.',
    category:    'github',
    schemaDef:   {
      owner:     { type: 'string', description: 'Repository owner (username or organization)' },
      repo:      { type: 'string', description: 'Repository name' },
      title:     { type: 'string', description: 'Issue title' },
      body:      { type: 'string', optional: true, description: 'Issue body/description (markdown supported)' },
      labels:    { type: 'array', items: { type: 'string' }, optional: true, description: 'Labels to apply to the issue' },
      assignees: { type: 'array', items: { type: 'string' }, optional: true, description: 'GitHub usernames to assign' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_create_issue'),
  },
  {
    name:        'github_update_issue',
    description: 'Update an existing GitHub issue — edit title, body, labels, assignees, or state.',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Repository owner (username or organization)' },
      repo:         { type: 'string', description: 'Repository name' },
      issue_number: { type: 'number', description: 'Issue number' },
      title:        { type: 'string', optional: true, description: 'New title' },
      body:         { type: 'string', optional: true, description: 'New body' },
      state:        { type: 'enum', enum: ['open', 'closed'], optional: true, description: 'Set issue state' },
      labels:       { type: 'array', items: { type: 'string' }, optional: true, description: 'Replace labels' },
      assignees:    { type: 'array', items: { type: 'string' }, optional: true, description: 'Replace assignees' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./github_update_issue'),
  },
  {
    name:        'github_close_issue',
    description: 'Close a GitHub issue with an optional reason (completed or not_planned).',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Repository owner (username or organization)' },
      repo:         { type: 'string', description: 'Repository name' },
      issue_number: { type: 'number', description: 'Issue number' },
      reason:       { type: 'enum', enum: ['completed', 'not_planned'], optional: true, description: "Close reason (defaults to 'completed')" },
    },
    operationTypes: ['execute'],
    loader:         () => import('./github_close_issue'),
  },
  {
    name:        'github_create_pr',
    description: 'Create a pull request in a GitHub repository.',
    category:    'github',
    schemaDef:   {
      owner: { type: 'string', description: 'Repository owner (username or organization)' },
      repo:  { type: 'string', description: 'Repository name' },
      title: { type: 'string', description: 'Pull request title' },
      head:  { type: 'string', description: 'Branch containing your changes' },
      base:  { type: 'string', optional: true, description: "Branch to merge into (defaults to 'main')" },
      body:  { type: 'string', optional: true, description: 'Pull request description (markdown supported)' },
      draft: { type: 'boolean', optional: true, description: 'Create as a draft PR' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_create_pr'),
  },
  {
    name:        'github_ready_pr',
    description: 'Flip a draft pull request to "ready for review" (draft PRs cannot be merged). Uses the GraphQL markPullRequestReadyForReview mutation.',
    category:    'github',
    schemaDef:   {
      owner:       { type: 'string', description: 'Repository owner (username or organization)' },
      repo:        { type: 'string', description: 'Repository name' },
      pull_number: { type: 'number', description: 'Pull request number' },
    },
    operationTypes: ['update'],
    loader:         () => import('./github_ready_pr'),
  },
  {
    name:        'github_merge_pr',
    description: 'Merge a GitHub pull request. Destructive — refuses without {"confirm":true}. Supports merge, squash, and rebase methods.',
    category:    'github',
    schemaDef:   {
      owner:          { type: 'string', description: 'Repository owner.' },
      repo:           { type: 'string', description: 'Repository name.' },
      pull_number:    { type: 'number', description: 'PR number to merge.' },
      merge_method:   { type: 'string', optional: true, description: 'merge | squash | rebase (default "merge").' },
      commit_title:   { type: 'string', optional: true, description: 'Override commit title (squash and merge methods only).' },
      commit_message: { type: 'string', optional: true, description: 'Override commit body.' },
      confirm:        { type: 'boolean', description: 'Must be true to actually merge.' },
    },
    operationTypes: ['update'],
    loader:         () => import('./github_merge_pr'),
  },
  {
    name:        'github_create_release',
    description: 'Cut a GitHub release (and its git tag). Publishing a non-draft release is outward-facing — refuses without {"confirm":true}; use {"draft":true} for a safe draft. Supports auto-generated release notes.',
    category:    'github',
    schemaDef:   {
      owner:                  { type: 'string', description: 'Repository owner.' },
      repo:                   { type: 'string', description: 'Repository name.' },
      tag_name:               { type: 'string', description: 'Git tag for the release (created if it does not exist).' },
      target_commitish:       { type: 'string', optional: true, description: 'Branch or SHA the tag is created from (defaults to the repo default branch).' },
      name:                   { type: 'string', optional: true, description: 'Release title (defaults to the tag).' },
      body:                   { type: 'string', optional: true, description: 'Release notes (markdown).' },
      draft:                  { type: 'boolean', optional: true, description: 'Create as a draft (not published). No confirm needed.' },
      prerelease:             { type: 'boolean', optional: true, description: 'Mark as a prerelease.' },
      generate_release_notes: { type: 'boolean', optional: true, description: 'Auto-generate notes from merged PRs since the previous tag.' },
      confirm:                { type: 'boolean', optional: true, description: 'Must be true to publish a non-draft release.' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_create_release'),
  },
  {
    name:        'github_check_runs',
    description: 'List CI check runs for a ref (branch name, SHA, or tag). Use this to answer "is CI green?" — shows status / conclusion / timing for each check.',
    category:    'github',
    schemaDef:   {
      owner: { type: 'string', description: 'Repository owner.' },
      repo:  { type: 'string', description: 'Repository name.' },
      ref:   { type: 'string', description: 'Branch name, SHA, or tag to check.' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_check_runs'),
  },
  {
    name:        'github_trigger_workflow_run',
    description: 'Manually trigger a GitHub Actions workflow via workflow_dispatch. The target workflow must declare a workflow_dispatch trigger in its "on:" block.',
    category:    'github',
    schemaDef:   {
      owner:       { type: 'string', description: 'Repository owner.' },
      repo:        { type: 'string', description: 'Repository name.' },
      workflow_id: { type: 'string', description: 'Workflow filename (e.g. "ci.yml") or numeric id.' },
      ref:         { type: 'string', optional: true, description: 'Branch/tag/SHA to run on (default "main").' },
      inputs:      { type: 'object', optional: true, description: 'Input values declared in the workflow dispatch spec.' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./github_trigger_workflow_run'),
  },
  {
    name:        'git_branch',
    description: 'Create, switch, delete, or list git branches.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      action:       { type: 'enum', enum: ['list', 'create', 'switch', 'delete'], description: 'Branch action to perform' },
      branchName:   { type: 'string', optional: true, description: 'Branch name (required for create, switch, delete)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./git_branch'),
  },
  {
    name:        'git_status',
    description: 'Show the working tree status — current branch, staged/unstaged/untracked files.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./git_status'),
  },
  {
    name:        'git_log',
    description: 'Show commit history for a repository.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      limit:        { type: 'number', optional: true, description: 'Number of commits to show (defaults to 20)' },
      oneline:      { type: 'boolean', optional: true, description: 'One-line format (defaults to true)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./git_log'),
  },
  {
    name:        'git_diff',
    description: 'Show changes between working tree, staging area, or commits.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      staged:       { type: 'boolean', optional: true, description: 'Show staged (cached) changes only' },
      commitA:      { type: 'string', optional: true, description: 'First commit SHA for comparison' },
      commitB:      { type: 'string', optional: true, description: 'Second commit SHA for comparison' },
      filePath:     { type: 'string', optional: true, description: 'Limit diff to a specific file path' },
    },
    operationTypes: ['read'],
    loader:         () => import('./git_diff'),
  },
  {
    name:        'git_stash',
    description: 'Save, list, apply, pop, or drop stashed changes.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      action:       { type: 'enum', enum: ['save', 'list', 'apply', 'pop', 'drop'], description: 'Stash action to perform' },
      message:      { type: 'string', optional: true, description: 'Stash message (for save action)' },
      stashRef:     { type: 'string', optional: true, description: "Stash reference like 'stash@{0}' (for apply/pop/drop, defaults to stash@{0})" },
    },
    operationTypes: ['execute'],
    loader:         () => import('./git_stash'),
  },
  {
    name:        'git_checkout',
    description: 'Restore files from a commit or branch, or discard working tree changes.',
    category:    'github',
    schemaDef:   {
      absolutePath: { type: 'string', description: 'Absolute path to the git repository (or any path inside it)' },
      files:        { type: 'array', items: { type: 'string' }, description: 'Absolute file paths to restore' },
      ref:          { type: 'string', optional: true, description: 'Commit SHA or branch to restore from (defaults to HEAD)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./git_checkout'),
  },

  // ── Repo management ──────────────────────────────────────────────────────
  {
    name:        'github_create_repo',
    description: 'Create a new GitHub repository for the authenticated user or an organization.',
    category:    'github',
    schemaDef:   {
      name:        { type: 'string', description: 'Repository name' },
      owner:       { type: 'string', optional: true, description: 'Organization name (required when org:true)' },
      description: { type: 'string', optional: true, description: 'Short repository description' },
      private:     { type: 'boolean', optional: true, description: 'Create as private (default false)' },
      auto_init:   { type: 'boolean', optional: true, description: 'Initialize with a README (default true)' },
      org:         { type: 'boolean', optional: true, description: 'Create under an organization (requires owner)' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_create_repo'),
  },
  {
    name:        'github_get_repo',
    description: 'Get metadata and stats for a GitHub repository — stars, forks, language, topics, default branch, license, push times.',
    category:    'github',
    schemaDef:   {
      owner: { type: 'string', description: 'Repository owner (username or organization)' },
      repo:  { type: 'string', description: 'Repository name' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_get_repo'),
  },
  {
    name:        'github_list_repos',
    description: 'List repositories for the authenticated user, a specific user, or an organization.',
    category:    'github',
    schemaDef:   {
      owner: { type: 'string', optional: true, description: 'Username or org to list repos for (omit to list your own)' },
      org:   { type: 'boolean', optional: true, description: 'Treat owner as an organization' },
      type:  { type: 'enum', enum: ['all', 'owner', 'member', 'public', 'private', 'forks', 'sources'], optional: true, default: 'all', description: 'Repo type filter' },
      sort:  { type: 'enum', enum: ['created', 'updated', 'pushed', 'full_name'], optional: true, default: 'updated', description: 'Sort order' },
      limit: { type: 'number', optional: true, default: 20, description: 'Max repos to return (capped at 100)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_list_repos'),
  },
  {
    name:        'github_delete_repo',
    description: 'Permanently delete a GitHub repository. Irreversible — requires confirm:true AND confirm_name matching the repo name.',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Repository owner (username or organization)' },
      repo:         { type: 'string', description: 'Repository name' },
      confirm:      { type: 'boolean', description: 'Must be true to proceed (destructive)' },
      confirm_name: { type: 'string', description: 'Must exactly match the repo name as a second safety check' },
    },
    operationTypes: ['delete'],
    loader:         () => import('./github_delete_repo'),
  },
  {
    name:        'github_fork_repo',
    description: 'Fork a GitHub repository into the authenticated user\'s account or a specified organization.',
    category:    'github',
    schemaDef:   {
      owner:        { type: 'string', description: 'Owner of the repo to fork' },
      repo:         { type: 'string', description: 'Repository to fork' },
      organization: { type: 'string', optional: true, description: 'Fork into this org instead of personal account' },
      name:         { type: 'string', optional: true, description: 'Override the fork\'s name (default: same as source)' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_fork_repo'),
  },

  // ── Pull request lifecycle ────────────────────────────────────────────────
  {
    name:        'github_get_pr',
    description: 'Get full details of a specific pull request — head/base, diff stats, reviewer list, labels, mergeable state.',
    category:    'github',
    schemaDef:   {
      owner:       { type: 'string', description: 'Repository owner (username or organization)' },
      repo:        { type: 'string', description: 'Repository name' },
      pull_number: { type: 'number', description: 'Pull request number' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_get_pr'),
  },
  {
    name:        'github_list_prs',
    description: 'List pull requests in a repository with optional filters for state, base branch, head branch, and sort order.',
    category:    'github',
    schemaDef:   {
      owner: { type: 'string', description: 'Repository owner (username or organization)' },
      repo:  { type: 'string', description: 'Repository name' },
      state: { type: 'enum', enum: ['open', 'closed', 'all'], optional: true, default: 'open', description: 'PR state filter' },
      base:  { type: 'string', optional: true, description: 'Filter by base branch name' },
      head:  { type: 'string', optional: true, description: 'Filter by head branch name (or user:branch)' },
      sort:  { type: 'enum', enum: ['created', 'updated', 'popularity', 'long-running'], optional: true, default: 'updated', description: 'Sort order' },
      limit: { type: 'number', optional: true, default: 20, description: 'Max PRs to return (capped at 100)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_list_prs'),
  },
  {
    name:        'github_update_pr',
    description: 'Edit a pull request — update its title, body, base branch, or open/closed state.',
    category:    'github',
    schemaDef:   {
      owner:       { type: 'string', description: 'Repository owner (username or organization)' },
      repo:        { type: 'string', description: 'Repository name' },
      pull_number: { type: 'number', description: 'Pull request number' },
      title:       { type: 'string', optional: true, description: 'New title' },
      body:        { type: 'string', optional: true, description: 'New description (markdown)' },
      base:        { type: 'string', optional: true, description: 'New base branch to merge into' },
      state:       { type: 'enum', enum: ['open', 'closed'], optional: true, description: 'Reopen or close the PR' },
    },
    operationTypes: ['update'],
    loader:         () => import('./github_update_pr'),
  },
  {
    name:        'github_close_pr',
    description: 'Close a pull request without merging it. Requires confirm:true. Optionally posts a closing comment.',
    category:    'github',
    schemaDef:   {
      owner:       { type: 'string', description: 'Repository owner (username or organization)' },
      repo:        { type: 'string', description: 'Repository name' },
      pull_number: { type: 'number', description: 'Pull request number' },
      confirm:     { type: 'boolean', description: 'Must be true to close (prevents accidents)' },
      comment:     { type: 'string', optional: true, description: 'Optional closing comment to post on the PR' },
    },
    operationTypes: ['update'],
    loader:         () => import('./github_close_pr'),
  },
  {
    name:        'github_add_pr_review',
    description: 'Submit a pull request review — APPROVE, REQUEST_CHANGES, or COMMENT. Body is required for REQUEST_CHANGES and COMMENT.',
    category:    'github',
    schemaDef:   {
      owner:       { type: 'string', description: 'Repository owner (username or organization)' },
      repo:        { type: 'string', description: 'Repository name' },
      pull_number: { type: 'number', description: 'Pull request number' },
      event:       { type: 'enum', enum: ['APPROVE', 'REQUEST_CHANGES', 'COMMENT'], description: 'Review action to take' },
      body:        { type: 'string', optional: true, description: 'Review summary comment (required for REQUEST_CHANGES and COMMENT)' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_add_pr_review'),
  },
  {
    name:        'github_list_pr_reviews',
    description: 'List all reviews on a pull request with their state (APPROVED, CHANGES_REQUESTED, COMMENTED, DISMISSED) and authors.',
    category:    'github',
    schemaDef:   {
      owner:       { type: 'string', description: 'Repository owner (username or organization)' },
      repo:        { type: 'string', description: 'Repository name' },
      pull_number: { type: 'number', description: 'Pull request number' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_list_pr_reviews'),
  },
  {
    name:        'github_request_pr_reviewers',
    description: 'Request specific users or teams to review a pull request.',
    category:    'github',
    schemaDef:   {
      owner:          { type: 'string', description: 'Repository owner (username or organization)' },
      repo:           { type: 'string', description: 'Repository name' },
      pull_number:    { type: 'number', description: 'Pull request number' },
      reviewers:      { type: 'array', items: { type: 'string' }, optional: true, description: 'GitHub usernames to request review from' },
      team_reviewers: { type: 'array', items: { type: 'string' }, optional: true, description: 'Team slugs to request review from' },
    },
    operationTypes: ['create'],
    loader:         () => import('./github_request_pr_reviewers'),
  },
  {
    name:        'github_get_pr_files',
    description: 'List all files changed in a pull request with their status (added/modified/removed/renamed) and line diff counts.',
    category:    'github',
    schemaDef:   {
      owner:       { type: 'string', description: 'Repository owner (username or organization)' },
      repo:        { type: 'string', description: 'Repository name' },
      pull_number: { type: 'number', description: 'Pull request number' },
    },
    operationTypes: ['read'],
    loader:         () => import('./github_get_pr_files'),
  },
];
