/**
 * Reflex thesaurus — maps the vocabulary people actually use onto canonical
 * Sulla concepts before tokenising ("llm" / "ai" → model, "add-ons" /
 * "extensions" → plugin, "note taker" / "transcript" → secretary).
 *
 * ReflexEngine is lexical: it can only match words it has seen. Applied to
 * both training examples and incoming messages, the thesaurus lets one seed
 * example cover every synonym. Benchmarked against a held-out newcomer set:
 * recall at zero false fires rose from 12% to 51% with this map alone.
 *
 * Multi-word phrases are replaced first (longest first), then single words.
 * Keep entries domain-level; a word that is also a common verb ("store",
 * "finish") must not be mapped, or it rewrites unrelated requests.
 */

export const REFLEX_PHRASES: Record<string, string> = {
  'password manager':       'vault',
  'api keys':               'vault',
  'api key':                'vault',
  'api tokens':             'vault',
  'api token':              'vault',
  'access token':           'vault',
  'access tokens':          'vault',
  'login details':          'vault',
  'add ons':                'plugin',
  'add-ons':                'plugin',
  'add on':                 'plugin',
  'add-on':                 'plugin',
  'connected apps':         'integration',
  'third party':            'integration',
  'hook up':                'connect',
  'hooked up':              'connect',
  'sign in to':             'connect',
  'log in to':              'connect',
  'work with':              'connect',
  'works with':             'connect',
  'every day':              'schedule',
  'every morning':          'schedule',
  'every night':            'schedule',
  'every week':             'schedule',
  'every monday':           'schedule',
  'every friday':           'schedule',
  'every hour':             'schedule',
  'on a schedule':          'schedule',
  'cron job':               'schedule',
  'cron jobs':              'schedule',
  'scheduled jobs':         'schedule',
  'scheduled job':          'schedule',
  'scheduled tasks':        'schedule',
  'scheduled task':         'schedule',
  'note taker':             'secretary',
  'note-taker':             'secretary',
  'meeting notes':          'secretary',
  'take notes':             'secretary',
  'taking notes':           'secretary',
  'meeting minutes':        'secretary',
  'to do':                  'task',
  'to-do':                  'task',
  'todo list':              'task',
  'to do list':             'task',
  'kanban board':           'kanban',
  'language model':         'model',
  'ai model':               'model',
  'local model':            'model local',
  'chat gpt':               'chatgpt',
  'gpt 4':                  'chatgpt',
  'gpt-4':                  'chatgpt',
  'speak out loud':         'voice',
  'talk out loud':          'voice',
  'read aloud':             'voice',
  'out loud':               'voice',
  'input device':           'microphone',
  'output device':          'speaker',
  'get started':            'onboard',
  'getting started':        'onboard',
  'first steps':            'onboard',
  'show me around':         'onboard tour',
  'walk me through':        'onboard tour',
  'set this up':            'onboard',
  'what do i do first':     'onboard',
  'what should i do first': 'onboard',
  'where do i start':       'onboard',
  'earlier conversation':   'history',
  'earlier conversations':  'history',
  'old conversation':       'history',
  'old conversations':      'history',
  'past conversation':      'history',
  'past conversations':     'history',
  'previous conversation':  'history',
  'previous conversations': 'history',
  'old chat':               'history',
  'old chats':              'history',
  'past chat':              'history',
  'past chats':             'history',
  'previous chat':          'history',
  'previous chats':         'history',
  'chat history':           'history',
  'earlier chat':           'history',
  'earlier chats':          'history',
  'app store':              'marketplace',
  'plugin store':           'marketplace plugin',
  'skill store':            'marketplace plugin',
  'extension store':        'marketplace plugin',
  'ask me before':          'approval',
  'ask before':             'approval',
  'ask permission':         'approval',
  'need permission':        'approval',
};

export const REFLEX_WORDS: Record<string, string> = {
  passwords:     'vault',
  password:      'vault',
  pw:            'vault',
  logins:        'vault',
  login:         'vault',
  credentials:   'vault',
  credential:    'vault',
  creds:         'vault',
  secrets:       'vault',
  secret:        'vault',
  keychain:      'vault',
  integrations:  'integration',
  integrate:     'integration',
  integrated:    'integration',
  connections:   'connect',
  connection:    'connect',
  link:          'connect',
  linking:       'connect',
  sync:          'connect',
  attach:        'connect',
  plug:          'connect',
  plugins:       'plugin',
  extensions:    'plugin',
  extension:     'plugin',
  addons:        'plugin',
  addon:         'plugin',
  skills:        'plugin',
  skill:         'plugin',
  templates:     'plugin',
  template:      'plugin',
  catalog:       'marketplace',
  automations:   'routine',
  automation:    'routine',
  automate:      'routine',
  automatically: 'routine',
  automatic:     'routine',
  routines:      'routine',
  workflows:     'routine',
  workflow:      'routine',
  recurring:     'schedule',
  scheduled:     'schedule',
  schedules:     'schedule',
  cron:          'schedule',
  daily:         'schedule',
  weekly:        'schedule',
  nightly:       'schedule',
  hourly:        'schedule',
  conversations: 'history',
  transcripts:   'history',
  agents:        'agent',
  assistants:    'agent',
  assistant:     'agent',
  bots:          'agent',
  bot:           'agent',
  employees:     'agent',
  employee:      'agent',
  tasks:         'task',
  todos:         'task',
  todo:          'task',
  tickets:       'task',
  ticket:        'task',
  issues:        'task',
  board:         'kanban',
  boards:        'kanban',
  projects:      'project',
  approvals:     'approval',
  permission:    'approval',
  permissions:   'approval',
  pending:       'approval',
  decisions:     'approval',
  transcribe:    'secretary',
  transcription: 'secretary',
  transcript:    'secretary',
  dictate:       'secretary',
  dictation:     'secretary',
  notetaker:     'secretary',
  minutes:       'secretary',
  preferences:   'settings',
  prefs:         'settings',
  options:       'settings',
  config:        'settings',
  configuration: 'settings',
  theme:         'appearance',
  dark:          'appearance',
  darker:        'appearance',
  light:         'appearance',
  colors:        'appearance',
  colour:        'appearance',
  color:         'appearance',
  ram:           'resources',
  memory:        'resources',
  cpu:           'resources',
  cpus:          'resources',
  disk:          'resources',
  models:        'model',
  llm:           'model',
  llms:          'model',
  ai:            'model',
  brain:         'model',
  gpt:           'chatgpt',
  openai:        'chatgpt',
  anthropic:     'claude',
  gemini:        'model',
  llama:         'ollama',
  mistral:       'model',
  lmstudio:      'ollama',
  mic:           'microphone',
  mics:          'microphone',
  microphones:   'microphone',
  headset:       'microphone',
  speakers:      'speaker',
  voices:        'voice',
  tts:           'voice',
  sound:         'audio',
  onboarding:    'onboard',
  tutorial:      'onboard tour',
  intro:         'onboard',
  introduction:  'onboard',
  beginner:      'onboard',
  doc:           'document',
  docs:          'document',
  documents:     'document',
  empty:         'blank',
  chats:         'chat',
  conversation:  'chat',
  internet:      'web',
  website:       'web',
  websites:      'web',
  browse:        'browser',
  browsing:      'browser',
  quit:          'stop',
  halt:          'stop',
  end:           'stop',
  ending:        'stop',
  cease:         'stop',
  silence:       'mute',
  begin:         'start',
  commence:      'start',
  kick:          'start',
  webcam:        'camera',
  webcams:       'camera',
  cameras:       'camera',
  cam:           'camera',
  displays:      'screen',
  display:       'screen',
  monitors:      'screen',
  monitor:       'screen',
  screens:       'screen',
};

const PHRASE_PATTERNS: [RegExp, string][] = Object.keys(REFLEX_PHRASES)
  .sort((a, b) => b.length - a.length)
  .map(p => [new RegExp(`\\b${ p.replace(/-/g, '[- ]?').replace(/ /g, '\\s+') }\\b`, 'g'), REFLEX_PHRASES[p]]);

/** Rewrite a message into canonical Reflex vocabulary (lower-cased). */
export function canonicalize(text: string): string {
  let t = ` ${ String(text).toLowerCase().replace(/[’']/g, '') } `;
  for (const [re, rep] of PHRASE_PATTERNS) t = t.replace(re, ` ${ rep } `);
  return t
    .split(/(\s+|[^a-z0-9]+)/)
    .map(w => (Object.prototype.hasOwnProperty.call(REFLEX_WORDS, w) ? REFLEX_WORDS[w] : w))
    .join('')
    .replace(/\s+/g, ' ')
    .trim();
}
