import type { Integration } from '../types';

export const nativeAiInfrastructureIntegrations: Record<string, Integration> = {
  mcp: {
    id:          'mcp',
    sort:        1,
    paid:        false,
    beta:        true,
    comingSoon:  false,
    name:        'MCP Server',
    description: 'Connect to a Model Context Protocol (MCP) server to access its tools, resources, and prompts.',
    category:    'AI Infrastructure',
    icon:        'mcp.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-03-18 00:00:00',
    developer:   'Open Standard',
    formGuide:   'Enter the URL of your MCP server endpoint and an optional auth token.',
    properties:  [
      {
        key:         'server_url',
        title:       'Server URL',
        hint:        'The MCP server endpoint URL (e.g. http://localhost:3001/mcp or https://mcp.example.com/sse).',
        type:        'url',
        required:    true,
        placeholder: 'http://localhost:3001/mcp',
      },
      {
        key:         'auth_token',
        title:       'Auth Token',
        hint:        'Optional bearer token for authenticating with the MCP server.',
        type:        'password',
        required:    false,
        placeholder: 'Bearer token or API key',
      },
    ],
  },

  'claude-code': {
    id:              'claude-code',
    sort:            1,
    paid:            true,
    beta:            true,
    comingSoon:      false,
    connected:       false,
    name:            'Claude Code',
    description:     'Run Anthropic\'s Claude Code agent inside the Sulla Desktop VM with full file access, bash, and web tools.',
    category:        'AI Infrastructure',
    icon:            'anthropic.svg',
    version:         '1.0.0',
    lastUpdated:     '2026-04-19',
    developer:       'Anthropic',
    oauth:           true,
    oauthProviderId: 'claude-code',
    formGuide:       'Sign in with Claude (recommended) or paste an Anthropic API key.',
    properties:      [
      {
        key:         'oauth_token',
        title:       'OAuth Token',
        hint:        'Populated automatically when you Sign in with Claude. Long-lived sk-ant-oat01-… token.',
        type:        'password',
        required:    false,
        placeholder: 'sk-ant-oat01-...',
      },
      {
        key:         'api_key',
        title:       'Anthropic API Key',
        hint:        'Optional — used if no OAuth token is present. Generate this in your Anthropic Console.',
        type:        'password',
        required:    false,
        placeholder: 'sk-ant-...',
      },
      {
        key:         'model',
        title:       'Model',
        hint:        'Claude Code chooses its own model; this field is informational.',
        type:        'text',
        required:    false,
        placeholder: 'claude-code',
      },
    ],
  },

  grok: {
    id:          'grok',
    sort:        2,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    name:        'Grok',
    description: 'Connect xAI Grok models for agent prompts and completions.',
    category:    'AI Infrastructure',
    icon:        'grok.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:42:00',
    developer:   'xAI',
    formGuide:   'Paste your xAI API key to enable Grok model access.',
    properties:  [
      {
        key:         'api_key',
        title:       'xAI API Key',
        hint:        'Generate this in your xAI developer console.',
        type:        'password',
        required:    true,
        placeholder: 'xai-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a Grok model to use for completions.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'grok_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  anthropic: {
    id:          'anthropic',
    sort:        3,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    name:        'Anthropic',
    description: 'Connect Anthropic Claude models for reasoning and assistant tasks.',
    category:    'AI Infrastructure',
    icon:        'anthropic.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:42:00',
    developer:   'Anthropic',
    formGuide:   'Paste your Anthropic API key to enable Claude model access.',
    properties:  [
      {
        key:         'api_key',
        title:       'Anthropic API Key',
        hint:        'Generate this in your Anthropic Console.',
        type:        'password',
        required:    true,
        placeholder: 'sk-ant-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a Claude model to use for completions.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'anthropic_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  openai: {
    id:              'openai',
    sort:            4,
    paid:            true,
    beta:            false,
    comingSoon:      false,
    name:            'OpenAI',
    description:     'Connect OpenAI models for chat, reasoning, and multimodal generation.',
    category:        'AI Infrastructure',
    icon:            'openai.svg',
    connected:       false,
    oauth:           true,
    oauthProviderId: 'openai',
    version:         '1.0.0',
    lastUpdated:     '2026-02-28 11:42:00',
    developer:       'OpenAI',
    formGuide:       'Paste your OpenAI API key or sign in with OAuth for unlimited access via your ChatGPT Plus/Pro subscription.',
    properties:      [
      {
        key:         'api_key',
        title:       'OpenAI API Key',
        hint:        'Generate this in your OpenAI dashboard.',
        type:        'password',
        required:    true,
        placeholder: 'sk-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select an OpenAI model to use for completions.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'openai_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  kimi: {
    id:          'kimi',
    sort:        5,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    name:        'Kimi',
    description: 'Connect Kimi models (Moonshot AI) for long-context generation tasks.',
    category:    'AI Infrastructure',
    icon:        'kimi.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:42:00',
    developer:   'Moonshot AI',
    formGuide:   'Paste your Kimi API key to enable Moonshot model access.',
    properties:  [
      {
        key:         'api_key',
        title:       'Kimi API Key',
        hint:        'Generate this in your Moonshot/Kimi developer console.',
        type:        'password',
        required:    true,
        placeholder: 'kimi-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a Kimi/Moonshot model to use.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'kimi_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  alibaba: {
    id:          'alibaba',
    sort:        6,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    name:        'Alibaba Cloud',
    description: 'Connect to Alibaba Cloud Model Studio (DashScope) for MiniMax, Kimi K2.5, and Qwen models.',
    category:    'AI Infrastructure',
    icon:        'alibaba.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-03-15 00:00:00',
    developer:   'Alibaba Cloud',
    formGuide:   'Paste your Alibaba Cloud DashScope API key to enable access to MiniMax, Kimi K2.5, Qwen, and other models.',
    properties:  [
      {
        key:         'api_key',
        title:       'DashScope API Key',
        hint:        'Generate this in your Alibaba Cloud Model Studio console (bailian.console.alibabacloud.com).',
        type:        'password',
        required:    true,
        placeholder: 'sk-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a model to use for completions.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'alibaba_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  nvidia: {
    id:          'nvidia',
    sort:        7,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    name:        'NVIDIA',
    description: 'Connect NVIDIA NIM and hosted inference endpoints for AI workloads.',
    category:    'AI Infrastructure',
    icon:        'nvidia.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:42:00',
    developer:   'NVIDIA',
    formGuide:   'Paste your NVIDIA API key to enable NIM/inference endpoint access.',
    properties:  [
      {
        key:         'api_key',
        title:       'NVIDIA API Key',
        hint:        'Generate this in NVIDIA Build / NGC account settings.',
        type:        'password',
        required:    true,
        placeholder: 'nvapi-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select an NVIDIA model to use.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'nvidia_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  cohere: {
    id:          'cohere',
    sort:        8,
    paid:        false,
    beta:        true,
    comingSoon:  false,
    name:        'Cohere',
    description: 'Connect to Cohere\'s free tier for Command A, Command A Reasoning, Command A Translate, Command A Vision, Command R, Command R+, Command R7B, and Command R7B Arabic. All models support tool use. 1,000 API calls/month (non-commercial use).',
    category:    'AI Infrastructure',
    icon:        'cohere.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-04-22 00:00:00',
    developer:   'Cohere',
    formGuide:   'Get your free trial API key from dashboard.cohere.com/api-keys. Free tier is limited to non-commercial use with 1,000 API calls per month. Only Command family models support tool use (Aya models do not).',
    properties:  [
      {
        key:         'api_key',
        title:       'Cohere API Key',
        hint:        'Free trial key from dashboard.cohere.com/api-keys',
        type:        'password',
        required:    true,
        placeholder: '...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a Cohere model to use.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'cohere_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  deepseek: {
    id:          'deepseek',
    sort:        8.5,
    paid:        false,
    beta:        true,
    comingSoon:  false,
    name:        'DeepSeek',
    description: 'Connect to DeepSeek AI for DeepSeek V4 Flash and V4 Pro models. All models support tool use. 500M tokens/day free tier. Note: deepseek-chat and deepseek-reasoner deprecated 2026/07/24.',
    category:    'AI Infrastructure',
    icon:        'deepseek.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-04-29 00:00:00',
    developer:   'DeepSeek',
    formGuide:   'Get your free API key from platform.deepseek.com. The free tier includes 500M tokens/day. Use deepseek-v4-flash (fast) or deepseek-v4-pro (most capable). Legacy names (deepseek-chat, deepseek-reasoner) deprecated 2026/07/24.',
    properties:  [
      {
        key:         'api_key',
        title:       'DeepSeek API Key',
        hint:        'Get your key from platform.deepseek.com',
        type:        'password',
        required:    true,
        placeholder: 'sk-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a DeepSeek model to use.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'deepseek_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  enterprise_gateway: {
    id:          'enterprise_gateway',
    sort:        9,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    name:        'Merchant Protocol Enterprise Gateway',
    description: 'Connect to your Enterprise Gateway for centralized LLM routing, voice services, agent management, and webhook orchestration.',
    category:    'AI Infrastructure',
    icon:        'merchant-protocol-shield.png',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-03-21 00:00:00',
    developer:   'Merchant Protocol',
    formGuide:   'Enter the URL of your Enterprise Gateway and an API key. You can create API keys from the gateway dashboard under API Keys.',
    properties:  [
      {
        key:         'gateway_url',
        title:       'Gateway URL',
        hint:        'The base URL of your Enterprise Gateway instance.',
        type:        'url',
        required:    true,
        placeholder: 'https://gateway.example.com',
      },
      {
        key:         'api_key',
        title:       'API Key',
        hint:        'Create this in the Enterprise Gateway dashboard under API Keys.',
        type:        'password',
        required:    true,
        placeholder: 'sk-...',
      },
    ],
  },

  google: {
    id:          'google',
    sort:        11,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    name:        'Google Gemini',
    description: 'Connect Google Gemini models including Gemini 2.0 Flash (free tier) for multimodal reasoning and coding.',
    category:    'AI Infrastructure',
    icon:        'google.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-04-25',
    developer:   'Google',
    formGuide:   'Get your free API key from aistudio.google.com/apikey. The free tier includes Gemini 2.0 Flash with generous rate limits.',
    properties:  [
      {
        key:         'api_key',
        title:       'Google AI Studio API Key',
        hint:        'Generate this for free at aistudio.google.com/apikey.',
        type:        'password',
        required:    true,
        placeholder: 'AIza...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a Gemini model. Gemini 2.0 Flash is free-tier.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'google_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  groq: {
    id:          'groq',
    sort:        12,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    name:        'Groq',
    description: 'Ultra-fast free-tier inference for Llama 4, DeepSeek R1, Qwen 2.5 Coder, and more — powered by Groq LPU hardware.',
    category:    'AI Infrastructure',
    icon:        'groq.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-04-25',
    developer:   'Groq',
    formGuide:   'Get your free API key at console.groq.com/keys. Free tier has generous daily limits with extremely fast inference.',
    properties:  [
      {
        key:         'api_key',
        title:       'Groq API Key',
        hint:        'Generate this for free at console.groq.com/keys.',
        type:        'password',
        required:    true,
        placeholder: 'gsk_...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a model. Llama 4 Scout and DeepSeek R1 are great for coding.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'groq_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  mistral: {
    id:          'mistral',
    sort:        13,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    name:        'Mistral AI',
    description: 'Access Mistral models including the free-tier Codestral — purpose-built for code generation, completion, and explanation.',
    category:    'AI Infrastructure',
    icon:        'mistral.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-04-25',
    developer:   'Mistral AI',
    formGuide:   'Get your API key at console.mistral.ai/api-keys. Codestral is available free for non-commercial use.',
    properties:  [
      {
        key:         'api_key',
        title:       'Mistral API Key',
        hint:        'Generate this at console.mistral.ai/api-keys.',
        type:        'password',
        required:    true,
        placeholder: '...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a model. Codestral is optimized for coding tasks.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'mistral_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  cerebras: {
    id:          'cerebras',
    sort:        14,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    name:        'Cerebras',
    description: 'Extremely fast free-tier inference on Cerebras wafer-scale chips. Run Llama 3.3 70B and Qwen 3 at speeds up to 2000 tokens/sec.',
    category:    'AI Infrastructure',
    icon:        'cerebras.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-04-25',
    developer:   'Cerebras',
    formGuide:   'Get your free API key at cloud.cerebras.ai. Free tier offers generous rate limits at very high inference speeds.',
    properties:  [
      {
        key:         'api_key',
        title:       'Cerebras API Key',
        hint:        'Generate this for free at cloud.cerebras.ai.',
        type:        'password',
        required:    true,
        placeholder: 'csk-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a model. Llama 3.3 70B is the most capable free option.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'cerebras_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  together: {
    id:          'together',
    sort:        15,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    name:        'Together AI',
    description: 'Access 100+ open-source models including DeepSeek V3, Qwen 2.5 Coder, and Llama 4. Free credits on signup.',
    category:    'AI Infrastructure',
    icon:        'together.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-04-25',
    developer:   'Together AI',
    formGuide:   'Sign up at api.together.ai for free credits. Get your API key from api.together.ai/settings/api-keys.',
    properties:  [
      {
        key:         'api_key',
        title:       'Together AI API Key',
        hint:        'Generate this at api.together.ai/settings/api-keys.',
        type:        'password',
        required:    true,
        placeholder: '...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a model. DeepSeek V3 and Qwen 2.5 Coder are top coding picks.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'together_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  ollama: {
    id:          'ollama',
    sort:        16,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    name:        'Ollama',
    description: 'Run open-source models locally for free — zero rate limits, full privacy. Supports CodeLlama, DeepSeek Coder, Qwen 2.5 Coder, and more.',
    category:    'AI Infrastructure',
    icon:        'ollama.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-04-25',
    developer:   'Ollama',
    formGuide:   'Install Ollama at ollama.com, then pull models with `ollama pull <model>`. If running on host Mac, use http://host.lima.internal:11434/v1 as the base URL.',
    properties:  [
      {
        key:         'base_url',
        title:       'Base URL',
        hint:        'Default: http://localhost:11434/v1. Use http://host.lima.internal:11434/v1 if Ollama is running on your Mac.',
        type:        'url',
        required:    true,
        placeholder: 'http://localhost:11434/v1',
      },
      {
        key:         'api_key',
        title:       'API Key (optional)',
        hint:        'Leave blank — Ollama does not require authentication by default.',
        type:        'password',
        required:    false,
        placeholder: 'ollama',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select from your locally installed models (pulled via `ollama pull`).',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'ollama_models',
        selectDependsOn: ['base_url'],
      },
    ],
  },

  custom: {
    id:          'custom',
    sort:        10,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    name:        'Custom',
    description: 'Connect a custom AI provider endpoint using your own base URL.',
    category:    'AI Infrastructure',
    icon:        'custom.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:46:00',
    developer:   'Custom',
    formGuide:   'Enter the base URL for your custom AI provider endpoint.',
    properties:  [
      {
        key:         'base_url',
        title:       'Base URL',
        hint:        'Required. Provide the API base URL for your custom AI provider.',
        type:        'url',
        required:    true,
        placeholder: 'https://api.example.com/v1',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a model from your custom endpoint (fetched from /models).',
        type:            'select',
        required:        false,
        placeholder:     'Select a model...',
        selectBoxId:     'custom_models',
        selectDependsOn: ['base_url', 'api_key'],
      },
    ],
  },

};
