import type { Integration } from '../types';

export const nativeAiInfrastructureIntegrations: Record<string, Integration> = {
  mcp: {
    id:          'mcp',
    sort:        1,
    paid:        false,
    beta:        true,
    comingSoon:  false,
    name:        'MCP Server',
    description: 'Connect to a Model Context Protocol (MCP) server to access its tools, resources, and prompts.',
    category:    'AI Infrastructure',
    icon:        'mcp.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-03-18 00:00:00',
    developer:   'Open Standard',
    formGuide:   'Enter the URL of your MCP server endpoint and an optional auth token.',
    properties:  [
      {
        key:         'server_url',
        title:       'Server URL',
        hint:        'The MCP server endpoint URL (e.g. http://localhost:3001/mcp or https://mcp.example.com/sse).',
        type:        'url',
        required:    true,
        placeholder: 'http://localhost:3001/mcp',
      },
      {
        key:         'auth_token',
        title:       'Auth Token',
        hint:        'Optional bearer token for authenticating with the MCP server.',
        type:        'password',
        required:    false,
        placeholder: 'Bearer token or API key',
      },
    ],
  },

  'claude-code': {
    id:              'claude-code',
    sort:            1,
    paid:            true,
    beta:            true,
    comingSoon:      false,
    connected:       false,
    name:            'Claude Code',
    description:     'Run Anthropic\'s Claude Code agent inside the Sulla Desktop VM with full file access, bash, and web tools.',
    category:        'AI Infrastructure',
    icon:            'anthropic.svg',
    version:         '1.0.0',
    lastUpdated:     '2026-04-19',
    developer:       'Anthropic',
    oauth:           true,
    oauthProviderId: 'claude-code',
    formGuide:       'Sign in with Claude (recommended) or paste an Anthropic API key.',
    properties:      [
      {
        key:         'oauth_token',
        title:       'OAuth Token',
        hint:        'Populated automatically when you Sign in with Claude. Long-lived sk-ant-oat01-… token.',
        type:        'password',
        required:    false,
        placeholder: 'sk-ant-oat01-...',
      },
      {
        key:         'api_key',
        title:       'Anthropic API Key',
        hint:        'Optional — used if no OAuth token is present. Generate this in your Anthropic Console.',
        type:        'password',
        required:    false,
        placeholder: 'sk-ant-...',
      },
      {
        key:         'model',
        title:       'Model',
        hint:        'Claude Code chooses its own model; this field is informational.',
        type:        'text',
        required:    false,
        placeholder: 'claude-code',
      },
    ],
  },

  grok: {
    id:          'grok',
    sort:        2,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    name:        'Grok',
    description: 'Connect xAI Grok models for agent prompts and completions.',
    category:    'AI Infrastructure',
    icon:        'grok.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:42:00',
    developer:   'xAI',
    formGuide:   'Paste your xAI API key to enable Grok model access.',
    properties:  [
      {
        key:         'api_key',
        title:       'xAI API Key',
        hint:        'Generate this in your xAI developer console.',
        type:        'password',
        required:    true,
        placeholder: 'xai-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a Grok model to use for completions.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'grok_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  anthropic: {
    id:          'anthropic',
    sort:        3,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    name:        'Anthropic',
    description: 'Connect Anthropic Claude models for reasoning and assistant tasks.',
    category:    'AI Infrastructure',
    icon:        'anthropic.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:42:00',
    developer:   'Anthropic',
    formGuide:   'Paste your Anthropic API key to enable Claude model access.',
    properties:  [
      {
        key:         'api_key',
        title:       'Anthropic API Key',
        hint:        'Generate this in your Anthropic Console.',
        type:        'password',
        required:    true,
        placeholder: 'sk-ant-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a Claude model to use for completions.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'anthropic_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  openai: {
    id:              'openai',
    sort:            4,
    paid:            true,
    beta:            false,
    comingSoon:      false,
    name:            'OpenAI',
    description:     'Connect OpenAI models for chat, reasoning, and multimodal generation.',
    category:        'AI Infrastructure',
    icon:            'openai.svg',
    connected:       false,
    oauth:           true,
    oauthProviderId: 'openai',
    version:         '1.0.0',
    lastUpdated:     '2026-02-28 11:42:00',
    developer:       'OpenAI',
    formGuide:       'Paste your OpenAI API key or sign in with OAuth for unlimited access via your ChatGPT Plus/Pro subscription.',
    properties:      [
      {
        key:         'api_key',
        title:       'OpenAI API Key',
        hint:        'Generate this in your OpenAI dashboard.',
        type:        'password',
        required:    true,
        placeholder: 'sk-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select an OpenAI model to use for completions.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'openai_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  kimi: {
    id:          'kimi',
    sort:        5,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    name:        'Kimi',
    description: 'Connect Kimi models (Moonshot AI) for long-context generation tasks.',
    category:    'AI Infrastructure',
    icon:        'kimi.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:42:00',
    developer:   'Moonshot AI',
    formGuide:   'Paste your Kimi API key to enable Moonshot model access.',
    properties:  [
      {
        key:         'api_key',
        title:       'Kimi API Key',
        hint:        'Generate this in your Moonshot/Kimi developer console.',
        type:        'password',
        required:    true,
        placeholder: 'kimi-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a Kimi/Moonshot model to use.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'kimi_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  alibaba: {
    id:          'alibaba',
    sort:        6,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    name:        'Alibaba Cloud',
    description: 'Connect to Alibaba Cloud Model Studio (DashScope) for MiniMax, Kimi K2.5, and Qwen models.',
    category:    'AI Infrastructure',
    icon:        'alibaba.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-03-15 00:00:00',
    developer:   'Alibaba Cloud',
    formGuide:   'Paste your Alibaba Cloud DashScope API key to enable access to MiniMax, Kimi K2.5, Qwen, and other models.',
    properties:  [
      {
        key:         'api_key',
        title:       'DashScope API Key',
        hint:        'Generate this in your Alibaba Cloud Model Studio console (bailian.console.alibabacloud.com).',
        type:        'password',
        required:    true,
        placeholder: 'sk-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a model to use for completions.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'alibaba_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  nvidia: {
    id:          'nvidia',
    sort:        7,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    name:        'NVIDIA',
    description: 'Connect NVIDIA NIM and hosted inference endpoints for AI workloads.',
    category:    'AI Infrastructure',
    icon:        'nvidia.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:42:00',
    developer:   'NVIDIA',
    formGuide:   'Paste your NVIDIA API key to enable NIM/inference endpoint access.',
    properties:  [
      {
        key:         'api_key',
        title:       'NVIDIA API Key',
        hint:        'Generate this in NVIDIA Build / NGC account settings.',
        type:        'password',
        required:    true,
        placeholder: 'nvapi-...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select an NVIDIA model to use.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'nvidia_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  cohere: {
    id:          'cohere',
    sort:        8,
    paid:        false,
    beta:        true,
    comingSoon:  false,
    name:        'Cohere',
    description: 'Connect to Cohere\'s free tier for Command A, Command A Reasoning, Command A Translate, Command A Vision, Command R, Command R+, Command R7B, and Command R7B Arabic. All models support tool use. 1,000 API calls/month (non-commercial use).',
    category:    'AI Infrastructure',
    icon:        'cohere.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-04-22 00:00:00',
    developer:   'Cohere',
    formGuide:   'Get your free trial API key from dashboard.cohere.com/api-keys. Free tier is limited to non-commercial use with 1,000 API calls per month. Only Command family models support tool use (Aya models do not).',
    properties:  [
      {
        key:         'api_key',
        title:       'Cohere API Key',
        hint:        'Free trial key from dashboard.cohere.com/api-keys',
        type:        'password',
        required:    true,
        placeholder: '...',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a Cohere model to use.',
        type:            'select',
        required:        true,
        placeholder:     'Select a model...',
        selectBoxId:     'cohere_models',
        selectDependsOn: ['api_key'],
      },
    ],
  },

  enterprise_gateway: {
    id:          'enterprise_gateway',
    sort:        9,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    name:        'Merchant Protocol Enterprise Gateway',
    description: 'Connect to your Enterprise Gateway for centralized LLM routing, voice services, agent management, and webhook orchestration.',
    category:    'AI Infrastructure',
    icon:        'merchant-protocol-shield.png',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-03-21 00:00:00',
    developer:   'Merchant Protocol',
    formGuide:   'Enter the URL of your Enterprise Gateway and an API key. You can create API keys from the gateway dashboard under API Keys.',
    properties:  [
      {
        key:         'gateway_url',
        title:       'Gateway URL',
        hint:        'The base URL of your Enterprise Gateway instance.',
        type:        'url',
        required:    true,
        placeholder: 'https://gateway.example.com',
      },
      {
        key:         'api_key',
        title:       'API Key',
        hint:        'Create this in the Enterprise Gateway dashboard under API Keys.',
        type:        'password',
        required:    true,
        placeholder: 'sk-...',
      },
    ],
  },

  custom: {
    id:          'custom',
    sort:        10,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    name:        'Custom',
    description: 'Connect a custom AI provider endpoint using your own base URL.',
    category:    'AI Infrastructure',
    icon:        'custom.svg',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:46:00',
    developer:   'Custom',
    formGuide:   'Enter the base URL for your custom AI provider endpoint.',
    properties:  [
      {
        key:         'base_url',
        title:       'Base URL',
        hint:        'Required. Provide the API base URL for your custom AI provider.',
        type:        'url',
        required:    true,
        placeholder: 'https://api.example.com/v1',
      },
      {
        key:             'model',
        title:           'Model',
        hint:            'Select a model from your custom endpoint (fetched from /models).',
        type:            'select',
        required:        false,
        placeholder:     'Select a model...',
        selectBoxId:     'custom_models',
        selectDependsOn: ['base_url', 'api_key'],
      },
    ],
  },

};
