import type { Integration } from '../types';

export const nativeFileStorageIntegrations: Record<string, Integration> = {
  google_drive: {
    id:          'google_drive',
    sort:        1,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Google Drive',
    description: 'Upload, download, and manage files and folders in Google Drive.',
    category:    'File Storage',
    icon:        'google_drive.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Google',
  },
  dropbox: {
    id:          'dropbox',
    sort:        2,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Dropbox',
    description: 'Upload, download, and manage files. Share folders and automate file sync workflows.',
    category:    'File Storage',
    icon:        'dropbox.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Dropbox',
  },
  onedrive: {
    id:          'onedrive',
    sort:        3,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'OneDrive',
    description: 'Manage files and folders in Microsoft OneDrive. Automate document storage workflows.',
    category:    'File Storage',
    icon:        'onedrive.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Microsoft',
  },
  box: {
    id:          'box',
    sort:        4,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Box',
    description: 'Upload, download, and manage enterprise content in Box. Automate file collaboration.',
    category:    'File Storage',
    icon:        'box.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Box',
  },
  aws_s3: {
    id:          'aws_s3',
    sort:        5,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'AWS S3',
    description: 'Upload, download, and manage objects in Amazon S3 buckets.',
    category:    'File Storage',
    icon:        'aws_s3.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Amazon',
  },
  backblaze_b2: {
    id:          'backblaze_b2',
    sort:        6,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Backblaze B2',
    description: 'Manage cloud storage buckets and files with S3-compatible API access.',
    category:    'File Storage',
    icon:        'backblaze_b2.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Backblaze',
  },
  sharepoint: {
    id:          'sharepoint',
    sort:        7,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'SharePoint',
    description: 'Manage document libraries, lists, and sites in Microsoft SharePoint.',
    category:    'File Storage',
    icon:        'sharepoint.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Microsoft',
  },
  google_cloud_storage: {
    id:          'google_cloud_storage',
    sort:        8,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Google Cloud Storage',
    description: 'Upload, download, and manage objects in GCS buckets.',
    category:    'File Storage',
    icon:        'google_cloud_storage.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Google',
  },
  wasabi: {
    id:          'wasabi',
    sort:        9,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Wasabi',
    description: 'Manage S3-compatible hot cloud storage with no egress or API fees.',
    category:    'File Storage',
    icon:        'wasabi.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Wasabi',
  },
  minio: {
    id:          'minio',
    sort:        10,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'MinIO',
    description: 'Manage self-hosted S3-compatible object storage buckets and objects.',
    category:    'File Storage',
    icon:        'minio.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'MinIO',
  },
  sftp: {
    id:          'sftp',
    sort:        11,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'SFTP / FTP',
    description: 'Upload, download, and manage files on remote servers via SFTP or FTP.',
    category:    'File Storage',
    icon:        'sftp.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Native',
  },
  cloudinary: {
    id:          'cloudinary',
    sort:        12,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Cloudinary',
    description: 'Upload, transform, and deliver images and videos via the Cloudinary API.',
    category:    'File Storage',
    icon:        'cloudinary.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Cloudinary',
  },
  uploadthing: {
    id:          'uploadthing',
    sort:        13,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'UploadThing',
    description: 'Upload and manage files with a developer-friendly file hosting API.',
    category:    'File Storage',
    icon:        'uploadthing.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'UploadThing',
  },
  azure_blob: {
    id:          'azure_blob',
    sort:        14,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Azure Blob Storage',
    description: 'Manage containers and blobs in Microsoft Azure Blob Storage.',
    category:    'File Storage',
    icon:        'azure_blob.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Microsoft',
  },
  r2: {
    id:          'r2',
    sort:        15,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Cloudflare R2',
    description: 'Manage S3-compatible object storage with zero egress fees on Cloudflare.',
    category:    'File Storage',
    icon:        'r2.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Cloudflare',
    formGuide:   'Create R2 API credentials under R2 → Manage R2 API Tokens in the Cloudflare dashboard. The S3 endpoint uses your Account ID.',
    properties:  [
      {
        key:         'account_id',
        title:       'Account ID',
        hint:        'Your Cloudflare Account ID — shown in the right sidebar of the dashboard. Also used to construct your S3 endpoint URL.',
        type:        'text',
        required:    true,
        placeholder: 'e.g. 44b9670fe26b5a11b117315215b8fed6',
      },
      {
        key:         'access_key_id',
        title:       'Access Key ID',
        hint:        'The Access Key ID from your R2 API token (created under R2 → Manage R2 API Tokens).',
        type:        'text',
        required:    true,
        placeholder: 'R2 Access Key ID',
      },
      {
        key:         'secret_access_key',
        title:       'Secret Access Key',
        hint:        'The Secret Access Key paired with your Access Key ID. Only shown once at creation time.',
        type:        'password',
        required:    true,
        placeholder: 'R2 Secret Access Key',
      },
      {
        key:         's3_endpoint',
        title:       'S3 API Endpoint',
        hint:        'Your R2 S3-compatible endpoint: https://<account_id>.r2.cloudflarestorage.com',
        type:        'url',
        required:    true,
        placeholder: 'https://<account_id>.r2.cloudflarestorage.com',
      },
    ],
  },
  imgbb: {
    id:          'imgbb',
    sort:        16,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'ImgBB',
    description: 'Upload and host images with direct links and thumbnail generation.',
    category:    'File Storage',
    icon:        'imgbb.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'ImgBB',
  },
};
