import type { Integration } from '../types';

export const nativeSecurityIntegrations: Record<string, Integration> = {
  apple_signin: {
    id:                'apple_signin',
    sort:              0,
    paid:              false,
    beta:              false,
    comingSoon:        false,
    connected:         false,
    name:              'Sign in with Apple',
    description:       'Sign in to Sulla Cloud with your Apple ID — the same account used by the Sulla Mobile app. Opens a secure browser window to Apple, then stores your session locally in this vault.',
    category:          'Security',
    icon:              'apple.svg',
    version:           '1.0.0',
    lastUpdated:       '2026-04-19',
    developer:         'Sulla',
    authType:          'oauth',
    oauthProviderId:   'apple',
    sullaManagedOAuth: true,
    formGuide:         'No configuration required — click "Sign in with Apple" to start. Sulla manages the OAuth app registration on your behalf.',
  },
  website: {
    id:          'website',
    sort:        1,
    paid:        false,
    beta:        true,
    comingSoon:  false,
    name:        'Website',
    description: 'Save and autofill website login credentials. Each saved website becomes a separate account.',
    category:    'Security',
    connected:   false,
    version:     '1.0.0',
    lastUpdated: '2026-03-31',
    developer:   'Sulla',
    properties:  [
      {
        key:         'website_url',
        title:       'Website URL',
        hint:        'The login page URL for this website',
        type:        'url',
        required:    true,
        placeholder: 'https://example.com/login',
      },
      {
        key:         'username',
        title:       'Username / Email',
        hint:        'Your login username or email address',
        type:        'text',
        required:    true,
        placeholder: 'user@example.com',
      },
      {
        key:         'password',
        title:       'Password',
        hint:        'Your login password',
        type:        'password',
        required:    true,
        placeholder: '',
      },
      {
        key:         'notes',
        title:       'Notes',
        hint:        'Optional notes about this credential',
        type:        'text',
        required:    false,
        placeholder: 'e.g. 2FA enabled, recovery codes in safe',
      },
      {
        key:         'llm_access',
        title:       'AI Access Level',
        hint:        'Controls what the AI agent can do with this credential: none (default), metadata, autofill, or full',
        type:        'select',
        required:    false,
        placeholder: 'none',
        selectBoxId: 'vault_llm_access',
      },
    ],
  },
};
