import type { Integration } from './types';

/**
 * Curated popular integrations shown by default on the integrations page.
 * This is a hand-picked subset across categories — the "landing page" view.
 * Clicking a category in the sidebar lazy-loads the full native catalogs.
 */
export const popularIntegrations: Record<string, Integration> = {
  enterprise_gateway: {
    id:          'enterprise_gateway',
    sort:        1,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Merchant Protocol Enterprise Gateway',
    description: 'Connect to your Enterprise Gateway for centralized LLM routing, voice services, agent management, and webhook orchestration.',
    category:    'AI Infrastructure',
    icon:        'merchant-protocol-shield.png',
    version:     '1.0.0',
    lastUpdated: '2026-03-21 00:00:00',
    developer:   'Merchant Protocol',
  },
  slack: {
    id:          'slack',
    sort:        2,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Slack',
    description: 'Send notifications, share updates, and interact with team members through channels and direct messages.',
    category:    'Communication',
    icon:        'slack.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-06 21:00:00',
    developer:   'Sulla',
  },
  gmail: {
    id:          'gmail',
    sort:        3,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Gmail',
    description: 'Send, receive, and manage emails with automated workflows.',
    category:    'Communication',
    icon:        'gmail.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Google',
  },
  microsoft_teams: {
    id:          'microsoft_teams',
    sort:        4,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Microsoft Teams',
    description: 'Send messages, manage channels, and coordinate team communication.',
    category:    'Communication',
    icon:        'microsoft_teams.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Microsoft',
  },
  zoom: {
    id:          'zoom',
    sort:        5,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Zoom',
    description: 'Schedule meetings, manage webinars, and automate meeting workflows.',
    category:    'Communication',
    icon:        'zoom.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Zoom',
  },
  github: {
    id:          'github',
    sort:        6,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'GitHub',
    description: 'Manage repositories, pull requests, issues, and automations.',
    category:    'Developer Tools',
    icon:        'github.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-14 00:00:00',
    developer:   'Sulla',
  },
  jira: {
    id:          'jira',
    sort:        7,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Jira',
    description: 'Create and manage issues, sprints, and boards.',
    category:    'Project Management',
    icon:        'jira.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Atlassian',
  },
  notion: {
    id:          'notion',
    sort:        8,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Notion',
    description: 'Create and manage pages, databases, and team knowledge.',
    category:    'Productivity',
    icon:        'notion.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Notion',
  },
  google_drive: {
    id:          'google_drive',
    sort:        9,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Google Drive',
    description: 'Upload, download, and manage files and folders.',
    category:    'File Storage',
    icon:        'google_drive.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Google',
  },
  dropbox: {
    id:          'dropbox',
    sort:        10,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Dropbox',
    description: 'Store, sync, and share files and folders across teams.',
    category:    'File Storage',
    icon:        'dropbox.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Dropbox',
  },
  salesforce: {
    id:          'salesforce',
    sort:        11,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Salesforce',
    description: 'Manage leads, accounts, opportunities, and customer records.',
    category:    'CRM & Sales',
    icon:        'salesforce.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Salesforce',
  },
  hubspot: {
    id:          'hubspot',
    sort:        12,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'HubSpot',
    description: 'Manage contacts, deals, and pipelines.',
    category:    'CRM & Sales',
    icon:        'hubspot.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'HubSpot',
  },
  stripe: {
    id:          'stripe',
    sort:        13,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Stripe',
    description: 'Manage payments, subscriptions, and invoices.',
    category:    'Finance',
    icon:        'stripe.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Stripe',
  },
  quickbooks: {
    id:          'quickbooks',
    sort:        14,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'QuickBooks',
    description: 'Track invoices, expenses, customers, and accounting data.',
    category:    'Finance',
    icon:        'quickbooks.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Intuit',
  },
  shopify: {
    id:          'shopify',
    sort:        15,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Shopify',
    description: 'Manage products, orders, customers, and inventory.',
    category:    'E-Commerce',
    icon:        'shopify.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Shopify',
  },
  zendesk: {
    id:          'zendesk',
    sort:        16,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Zendesk',
    description: 'Manage tickets, users, and support workflows.',
    category:    'Customer Support',
    icon:        'zendesk.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Zendesk',
  },
  mailchimp: {
    id:          'mailchimp',
    sort:        17,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Mailchimp',
    description: 'Manage email campaigns, audiences, and lifecycle marketing.',
    category:    'Marketing',
    icon:        'mailchimp.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Intuit',
  },
  google_ads: {
    id:          'google_ads',
    sort:        18,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Google Ads',
    description: 'Manage ad campaigns, budgets, and performance reporting.',
    category:    'Marketing',
    icon:        'google_ads.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Google',
  },
  figma: {
    id:          'figma',
    sort:        19,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Figma',
    description: 'Access design files, components, and collaboration data.',
    category:    'Design',
    icon:        'figma.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Figma',
  },
  asana: {
    id:          'asana',
    sort:        20,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Asana',
    description: 'Coordinate team tasks, projects, and status tracking.',
    category:    'Project Management',
    icon:        'asana.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Asana',
  },
  trello: {
    id:          'trello',
    sort:        21,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Trello',
    description: 'Manage Kanban boards, cards, and team workflows.',
    category:    'Project Management',
    icon:        'trello.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28',
    developer:   'Atlassian',
  },
  openai: {
    id:          'openai',
    sort:        22,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'OpenAI',
    description: 'Connect OpenAI models for chat, reasoning, and multimodal tasks.',
    category:    'AI Infrastructure',
    icon:        'openai.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:42:00',
    developer:   'OpenAI',
  },
  anthropic: {
    id:          'anthropic',
    sort:        23,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Anthropic',
    description: 'Connect Claude models for agent reasoning and automation.',
    category:    'AI Infrastructure',
    icon:        'anthropic.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:42:00',
    developer:   'Anthropic',
  },
  ollama: {
    id:          'ollama',
    sort:        24,
    paid:        false,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Ollama',
    description: 'Run local or remote open-weight LLM models.',
    category:    'AI Infrastructure',
    icon:        'ollama.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28 12:45:00',
    developer:   'Ollama',
  },
  nvidia: {
    id:          'nvidia',
    sort:        25,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'NVIDIA',
    description: 'Connect NVIDIA-hosted models and inference endpoints.',
    category:    'AI Infrastructure',
    icon:        'nvidia.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:42:00',
    developer:   'NVIDIA',
  },
  grok: {
    id:          'grok',
    sort:        26,
    paid:        true,
    beta:        false,
    comingSoon:  false,
    connected:   false,
    name:        'Grok',
    description: 'Connect xAI Grok models for prompts and completions.',
    category:    'AI Infrastructure',
    icon:        'grok.svg',
    version:     '1.0.0',
    lastUpdated: '2026-02-28 11:42:00',
    developer:   'xAI',
  },
};
