import type { ToolManifest } from '../registry';

/**
 * Project-item tools — Projects project-state in Postgres (the issue ledger
 * behind the Projects view). Full CRUD across the hierarchy:
 *
 *   work_projects → work_epics → work_tasks (optional parent_id subtasks)
 *                                 + work_task_comments
 *
 * Explicit create_* / update_* / archive per record type — no combined
 * "upsert". Distinct from the filesystem `projects` category (PROJECT.md
 * PRDs). Soft-archive only; archiving cascades down.
 *
 * Vocabulary (free-text columns, but use these consistently):
 *   status   → backlog | todo | planning | in_progress | in_review | blocked | done | cancelled | parked
 *   priority → critical | high | medium | low
 */
const ITEM_STATUS_DESC = 'working | backlog | todo | planning | in_progress | in_review | blocked | done | cancelled | parked.';
const PROJECT_STATUS_DESC = 'working | backlog | blocked | done | cancelled | parked.';
const TASK_STATUS_DESC = 'backlog | todo | planning | in_progress | in_review | blocked | done | cancelled | parked.';
const PRIORITY_DESC = 'critical | high | medium | low.';

export const projectToolManifests: ToolManifest[] = [
  // ── reads ────────────────────────────────────────────────────────────
  {
    name:        'list_project_items',
    description: 'List Projects project-state from Postgres: projects, epics, and/or tasks. Filter by kind, status, priority, project, epic, parent task, or assignee. Default kind=task shows open work. This is the structured agenda — not the filesystem PROJECT.md PRDs.',
    category:    'project',
    schemaDef:   {
      kind:         { type: 'string', optional: true, description: 'What to list: "project", "epic", "task", or "all" (default "task").' },
      status:       { type: 'string', optional: true, description: `Filter by status: ${ ITEM_STATUS_DESC } Omit for all non-archived.` },
      priority:     { type: 'string', optional: true, description: `Filter by priority: ${ PRIORITY_DESC }` },
      project_id:   { type: 'string', optional: true, description: 'Limit to one project id (applies to epics + tasks).' },
      epic_id:      { type: 'string', optional: true, description: 'Limit to one epic id (tasks only).' },
      parent_id:    { type: 'string', optional: true, description: 'Limit to subtasks of this task id.' },
      assignee:     { type: 'string', optional: true, description: 'Filter tasks by canonical queue owner (dispatcher, heartbeat, or human).' },
      include_done: { type: 'boolean', optional: true, description: 'When true, include done/cancelled rows. Default false.' },
      limit:        { type: 'number', optional: true, description: 'Max rows per kind (default 50).' },
    },
    operationTypes: ['read'],
    loader:         () => import('./list_project_items'),
  },
  {
    name:        'get_project_item',
    description: 'Fetch one project item by id. Auto-detects project / epic / task. For a project, also returns its epics. For an epic, also returns its tasks. For a task, also returns comments and any subtasks.',
    category:    'project',
    schemaDef:   {
      id:                { type: 'string', description: 'Project item id (tiny id from list_project_items / create_*).' },
      kind:              { type: 'string', optional: true, description: 'Optional hint: "project", "epic", or "task". Omit to search all three.' },
      include_knowledge: { type: 'boolean', optional: true, description: 'Append a compact direct/inherited Knowledge Base association summary.' },
    },
    operationTypes: ['read'],
    loader:         () => import('./get_project_item'),
  },
  {
    name:        'search_project_items',
    description: 'Keyword search across project / epic / task titles and descriptions. Use before creating a new item to avoid duplicates, or to find work related to the current turn.',
    category:    'project',
    schemaDef:   {
      query:            { type: 'string', description: 'Search keyword or phrase.' },
      kind:             { type: 'string', optional: true, description: 'Limit to "project", "epic", or "task". Omit to search all three.' },
      limit:            { type: 'number', optional: true, description: 'Max results (default 20).' },
      include_archived: { type: 'boolean', optional: true, description: 'When true, also search archived rows. Default false.' },
    },
    operationTypes: ['read'],
    loader:         () => import('./search_project_items'),
  },
  {
    name:        'list_task_comments',
    description: 'List the comment thread on a task, oldest first. Comments are append-only history (progress notes, blockers, decisions).',
    category:    'project',
    schemaDef:   {
      task_id: { type: 'string', description: 'Task id whose comments to list.' },
    },
    operationTypes: ['read'],
    loader:         () => import('./list_task_comments'),
  },
  {
    name:        'project_report',
    description: 'Standup report: recent completions plus activity-rotated actionable, blocked-recovery, and planning queues with project/epic context. Optionally scope to one project or assignee. Use this for a quick "what moved and what\'s next" pulse.',
    category:    'project',
    schemaDef:   {
      hours:      { type: 'number', optional: true, description: 'Look-back window in hours for completed work (default 24).' },
      next_limit: { type: 'number', optional: true, description: 'How many upcoming tasks to list (default 15).' },
      project_id: { type: 'string', optional: true, description: 'Limit the report to one project id.' },
      assignee:   { type: 'string', optional: true, description: 'Limit to one canonical queue owner (dispatcher, heartbeat, or human).' },
    },
    operationTypes: ['read'],
    loader:         () => import('./project_report'),
  },
  {
    name:        'list_task_waits',
    description: 'Inspect durable external waits. Active unchanged waits are monitor-owned and should not be polled or commented on by Heartbeat.',
    category:    'project',
    schemaDef:   {
      task_id: { type: 'string', optional: true, description: 'Limit waits to one Projects task id.' },
      status:  { type: 'string', optional: true, description: 'active | changed | satisfied | cancelled | failed.' },
      limit:   { type: 'number', optional: true, description: 'Maximum rows (default 100).' },
    },
    operationTypes: ['read'],
    loader:         () => import('./list_task_waits'),
  },
  {
    name:        'register_task_wait',
    description: 'Register one durable external wait. Duplicate active task/kind/target registrations are idempotent. The monitor owns subsequent checks; register once and continue across the portfolio.',
    category:    'project',
    schemaDef:   {
      task_id:       { type: 'string', description: 'Projects task id.' },
      wait_kind:     { type: 'string', description: 'github_checks | human_gate | scheduled_time | external_job.' },
      target_key:    { type: 'string', description: 'Stable exact target identity, e.g. owner/repo#123 or gate:merge.' },
      target:        { type: 'object', description: 'Structured target. GitHub checks use owner, repo, and pullNumber or ref.' },
      fingerprint:   { type: 'string', optional: true, description: 'Exact already-observed fingerprint, when known.' },
      next_check_at: { type: 'string', optional: true, description: 'ISO time for the first monitor check.' },
      due_at:        { type: 'string', optional: true, description: 'Optional ISO threshold for event-driven gates/times.' },
      owner:         { type: 'string', optional: true, description: 'Monitor owner label.' },
      actor:         { type: 'string', optional: true, description: 'Comment attribution for the one initial registration comment.' },
    },
    operationTypes: ['create'],
    loader:         () => import('./register_task_wait'),
  },
  {
    name:        'cancel_task_wait',
    description: 'Cancel one active durable task wait by wait id. Terminal task states cancel waits automatically.',
    category:    'project',
    schemaDef:   {
      id:     { type: 'string', description: 'Wait id from list_task_waits.' },
      reason: { type: 'string', optional: true, description: 'Concise cancellation reason.' },
    },
    operationTypes: ['update'],
    loader:         () => import('./cancel_task_wait'),
  },
  {
    name:        'list_linked_knowledge',
    description: 'List direct Knowledge Base links for a Projects item and, when requested, inherited parent links.',
    category:    'project',
    schemaDef:   {
      item_kind:         { type: 'string', description: 'project, epic, or task.' },
      item_id:           { type: 'string', description: 'Projects item id.' },
      include_inherited: { type: 'boolean', optional: true, description: 'Include parent links; default true.' },
      relation_type:     { type: 'string', optional: true, description: 'Optional relation filter.' },
      include_archived:  { type: 'boolean', optional: true, description: 'Include archived links/nodes.' },
      limit:             { type: 'number', optional: true, description: 'Bounded result limit.' },
    },
    operationTypes: ['read'],
    loader:         () => import('./list_linked_knowledge'),
  },
  {
    name:        'link_knowledge_item',
    description: 'Attach an existing Knowledge Base node to exactly one Projects item through the shared association model.',
    category:    'project',
    schemaDef:   {
      item_kind:         { type: 'string', description: 'project, epic, or task.' },
      item_id:           { type: 'string', description: 'Projects item id.' },
      knowledge_node_id: { type: 'string', description: 'Knowledge Base node id.' },
      relation_type:     { type: 'string', optional: true, description: 'Soft relation vocabulary; defaults to related_to.' },
      note:              { type: 'string', optional: true, description: 'Optional association note.' },
      actor:             { type: 'string', optional: true, description: 'Agent/user attribution.' },
      source:            { type: 'string', optional: true, description: 'Mutation source.' },
    },
    operationTypes: ['create', 'update'],
    loader:         () => import('./link_knowledge_item'),
  },
  {
    name:        'unlink_knowledge_item',
    description: 'Soft-unlink one direct Knowledge Base association from a Projects item.',
    category:    'project',
    schemaDef:   {
      item_kind:         { type: 'string', description: 'project, epic, or task.' },
      item_id:           { type: 'string', description: 'Projects item id.' },
      knowledge_node_id: { type: 'string', description: 'Knowledge Base node id.' },
      relation_type:     { type: 'string', optional: true, description: 'Relation to unlink; defaults to related_to.' },
      actor:             { type: 'string', optional: true, description: 'Agent/user attribution.' },
      source:            { type: 'string', optional: true, description: 'Mutation source.' },
    },
    operationTypes: ['update'],
    loader:         () => import('./unlink_knowledge_item'),
  },

  {
    name:        'create_task_dependency',
    description: 'Create one first-class task dependency (dependent depends on a prerequisite). Rejects self-links and cycles transactionally. The dependent cannot be claimed for planning, execution, review, or lane entry until the prerequisite task is done.',
    category:    'project',
    schemaDef:   {
      dependent_task_id:    { type: 'string', description: 'The task that is blocked (the dependent).' },
      depends_on_task_id:   { type: 'string', description: 'The prerequisite task that must reach done first.' },
      relation_type:        { type: 'string', optional: true, description: 'blocks | requires | ordered-after. Default requires.' },
      acceptance_condition: { type: 'string', optional: true, description: 'Optional human-readable release condition, surfaced in explain_task_claimability.' },
      actor:                { type: 'string', optional: true, description: 'Attribution for the created dependency.' },
    },
    operationTypes: ['create'],
    loader:         () => import('./create_task_dependency'),
  },
  {
    name:        'remove_task_dependency',
    description: 'Remove (soft-archive) one task dependency by id, or by dependent_task_id + depends_on_task_id (+ relation_type). Use to explicitly override a failed/cancelled prerequisite; dependencies are never silently unblocked.',
    category:    'project',
    schemaDef:   {
      id:                 { type: 'string', optional: true, description: 'Dependency id from list_task_dependencies.' },
      dependent_task_id:  { type: 'string', optional: true, description: 'The dependent task (with depends_on_task_id).' },
      depends_on_task_id: { type: 'string', optional: true, description: 'The prerequisite task (with dependent_task_id).' },
      relation_type:      { type: 'string', optional: true, description: 'blocks | requires | ordered-after. Default requires.' },
    },
    operationTypes: ['update'],
    loader:         () => import('./remove_task_dependency'),
  },
  {
    name:        'list_task_dependencies',
    description: 'List a task dependencies (its prerequisites) and its dependents. Read-only.',
    category:    'project',
    schemaDef:   {
      task_id:          { type: 'string', description: 'Projects task id.' },
      include_archived: { type: 'boolean', optional: true, description: 'Include soft-archived dependencies.' },
    },
    operationTypes: ['read'],
    loader:         () => import('./list_task_dependencies'),
  },
  {
    name:        'explain_task_claimability',
    description: 'Explain whether a task is claimable: returns the transitive dependency chain and the exact reason a task is or is not claimable (unresolved prerequisites and their live status).',
    category:    'project',
    schemaDef:   {
      task_id: { type: 'string', description: 'Projects task id.' },
    },
    operationTypes: ['read'],
    loader:         () => import('./explain_task_claimability'),
  },
  // ── projects ─────────────────────────────────────────────────────────
  {
    name:        'create_project',
    description: 'Create a NEW project (top of the operator agenda). Always inserts a new row (a unique slug is resolved automatically). Use update_project to change an existing one. Distinct from the filesystem PROJECT.md PRD tooling.',
    category:    'project',
    schemaDef:   {
      title:          { type: 'string', description: 'Short project name.' },
      slug:           { type: 'string', optional: true, description: 'Stable slug (e.g. operator-transition). Auto-derived from title when omitted; suffixed if taken.' },
      description:    { type: 'string', optional: true, description: 'What this project is and what done looks like.' },
      outcome_metric: { type: 'string', optional: true, description: 'How you will know it is done.' },
      status:         { type: 'string', optional: true, description: `Status: ${ PROJECT_STATUS_DESC } Default backlog.` },
      priority:       { type: 'string', optional: true, description: `Priority: ${ PRIORITY_DESC } Default medium.` },
      owner:          { type: 'string', optional: true, description: 'Who owns the project (e.g. heartbeat, sulla, human).' },
      github_repo:    { type: 'string', optional: true, description: 'Optional owner/repo this project maps to.' },
      due_at:         { type: 'string', optional: true, description: 'ISO due date.' },
    },
    operationTypes: ['create'],
    loader:         () => import('./create_project'),
  },
  {
    name:        'update_project',
    description: 'Update an existing project in place (by id). Only the fields you pass change. Status / priority / due_at changes stamp last_moved_at.',
    category:    'project',
    schemaDef:   {
      id:             { type: 'string', description: 'Project id to update.' },
      title:          { type: 'string', optional: true, description: 'New project name.' },
      slug:           { type: 'string', optional: true, description: 'New stable slug.' },
      description:    { type: 'string', optional: true, description: 'Updated description.' },
      outcome_metric: { type: 'string', optional: true, description: 'Updated outcome metric.' },
      status:         { type: 'string', optional: true, description: `Status: ${ PROJECT_STATUS_DESC }` },
      priority:       { type: 'string', optional: true, description: `Priority: ${ PRIORITY_DESC }` },
      owner:          { type: 'string', optional: true, description: 'New owner, or empty string to unassign.' },
      github_repo:    { type: 'string', optional: true, description: 'owner/repo mapping.' },
      due_at:         { type: 'string', optional: true, description: 'ISO due date, or empty string to clear.' },
    },
    operationTypes: ['update'],
    loader:         () => import('./update_project'),
  },

  // ── epics ────────────────────────────────────────────────────────────
  {
    name:        'create_epic',
    description: 'Create a NEW epic under a project (the major chunks of a project). Always inserts a new row (unique slug within the project). Use update_epic to change an existing one.',
    category:    'project',
    schemaDef:   {
      project_id:  { type: 'string', description: 'Parent project id.' },
      title:       { type: 'string', description: 'Short epic name.' },
      slug:        { type: 'string', optional: true, description: 'Stable slug inside the project. Auto-derived from title when omitted; suffixed if taken.' },
      description: { type: 'string', optional: true, description: 'What this epic delivers.' },
      status:      { type: 'string', optional: true, description: `Status: ${ PROJECT_STATUS_DESC } Default todo.` },
      priority:    { type: 'string', optional: true, description: `Priority: ${ PRIORITY_DESC } Default medium.` },
      position:    { type: 'number', optional: true, description: 'Manual sort order inside the project (default 0).' },
      due_at:      { type: 'string', optional: true, description: 'ISO due date.' },
    },
    operationTypes: ['create'],
    loader:         () => import('./create_epic'),
  },
  {
    name:        'update_epic',
    description: 'Update an existing epic in place (by id). Only the fields you pass change. Pass project_id to move it to another project; pass position to reorder it inside the project. Status / priority / due_at / project moves stamp last_moved_at.',
    category:    'project',
    schemaDef:   {
      id:          { type: 'string', description: 'Epic id to update.' },
      project_id:  { type: 'string', optional: true, description: 'Move to another project id.' },
      title:       { type: 'string', optional: true, description: 'New epic name.' },
      slug:        { type: 'string', optional: true, description: 'New stable slug.' },
      description: { type: 'string', optional: true, description: 'Updated description.' },
      status:      { type: 'string', optional: true, description: `Status: ${ PROJECT_STATUS_DESC }` },
      priority:    { type: 'string', optional: true, description: `Priority: ${ PRIORITY_DESC }` },
      position:    { type: 'number', optional: true, description: 'Manual sort order inside the project.' },
      due_at:      { type: 'string', optional: true, description: 'ISO due date, or empty string to clear.' },
    },
    operationTypes: ['update'],
    loader:         () => import('./update_epic'),
  },

  // ── tasks ────────────────────────────────────────────────────────────
  {
    name:        'create_task',
    description: 'Create a NEW task (issue) under an epic. Always inserts a new row. Pass parent_id to nest a subtask under another task. Use update_task to change an existing one.',
    category:    'project',
    schemaDef:   {
      epic_id:      { type: 'string', description: 'Parent epic id.' },
      title:        { type: 'string', description: 'Task title.' },
      parent_id:    { type: 'string', optional: true, description: 'Parent task id when this is a subtask.' },
      description:  { type: 'string', optional: true, description: 'Issue-style body — what done looks like.' },
      status:       { type: 'string', optional: true, description: `Status: ${ TASK_STATUS_DESC } Defaults to the project's first execution lane; todo is used only in compatibility mode.` },
      priority:     { type: 'string', optional: true, description: `Priority: ${ PRIORITY_DESC } Default medium.` },
      assignee:     { type: 'string', optional: true, description: 'Queue owner: dispatcher (autonomous execution), heartbeat (supervision/review), or human. Legacy sulla ownership on ordinary todos is normalized to dispatcher.' },
      due_at:       { type: 'string', optional: true, description: 'ISO due date.' },
      labels:       { type: 'array', optional: true, description: 'String labels (e.g. ["gate","operator"]).' },
      github_issue: { type: 'string', optional: true, description: 'Optional owner/repo#n or URL mapping to a GitHub issue.' },
      position:     { type: 'number', optional: true, description: 'Manual sort order inside the epic (default 0).' },
      actor:        { type: 'string', optional: true, description: 'Acting source/agent for attribution: "heartbeat" (autonomous), "sulla" (chat), "workbench", or "human". Defaults to "sulla".' },
    },
    operationTypes: ['create'],
    loader:         () => import('./create_task'),
  },
  {
    name:        'update_task',
    description: 'Update an existing task in place (by id). Only the fields you pass change. This is also the MOVE op: pass epic_id to move it to another epic, status to change its board column, or position to reorder inside its epic. Moving status/priority/assignee/due_at/parent_id/epic_id stamps last_moved_at; done/cancelled also stamps completed_at.',
    category:    'project',
    schemaDef:   {
      id:           { type: 'string', description: 'Task id to update.' },
      epic_id:      { type: 'string', optional: true, description: 'Move to another epic id.' },
      parent_id:    { type: 'string', optional: true, description: 'Parent task id when nesting; empty string clears it.' },
      title:        { type: 'string', optional: true, description: 'New task title.' },
      description:  { type: 'string', optional: true, description: 'Updated body.' },
      status:       { type: 'string', optional: true, description: `Status: ${ TASK_STATUS_DESC }` },
      priority:     { type: 'string', optional: true, description: `Priority: ${ PRIORITY_DESC }` },
      assignee:     { type: 'string', optional: true, description: 'New queue owner (dispatcher, heartbeat, or human), or empty string to unassign. Legacy sulla ownership on ordinary todos is normalized to dispatcher.' },
      due_at:       { type: 'string', optional: true, description: 'ISO due date, or empty string to clear.' },
      labels:       { type: 'array', optional: true, description: 'String labels. Replaces the full set when provided.' },
      github_issue: { type: 'string', optional: true, description: 'owner/repo#n or URL, or empty string to clear.' },
      position:     { type: 'number', optional: true, description: 'Manual sort order inside the epic.' },
      actor:        { type: 'string', optional: true, description: 'Acting source/agent for attribution: "heartbeat" (autonomous), "sulla" (chat), "workbench", or "human". Defaults to "sulla".' },
    },
    operationTypes: ['update'],
    loader:         () => import('./update_task'),
  },

  // ── comments ─────────────────────────────────────────────────────────
  {
    name:        'add_task_comment',
    description: 'Add a note/comment on a task (GitHub-issue style). Append-only history — never edited or hard-deleted. Use for progress notes, blockers, and decisions; use update_task to change status/priority/due date. Author defaults to "sulla"; pass author="human" for the operator.',
    category:    'project',
    schemaDef:   {
      task_id: { type: 'string', description: 'Task id to comment on.' },
      body:    { type: 'string', description: 'Comment markdown/text.' },
      author:  { type: 'string', optional: true, description: 'Acting source/agent for attribution: "heartbeat" (autonomous), "sulla" (chat), "workbench", or "human". Defaults to "sulla".' },
      actor:   { type: 'string', optional: true, description: 'Alias for author. Acting source/agent for attribution: "heartbeat" (autonomous), "sulla" (chat), "workbench", or "human". Defaults to "sulla".' },
    },
    operationTypes: ['create'],
    loader:         () => import('./add_task_comment'),
  },

  // ── archive (soft-delete, cascades down) ─────────────────────────────
  {
    name:        'archive_project_item',
    description: 'Soft-archive a project, epic, or task by id. Never hard-deleted. Archiving a project also archives its epics + tasks; archiving an epic also archives its tasks. Recoverable via get_project_item / search with include_archived.',
    category:    'project',
    schemaDef:   {
      id:   { type: 'string', description: 'Project item id to archive.' },
      kind: { type: 'string', optional: true, description: 'Optional hint: "project", "epic", or "task". Omit to search all three.' },
    },
    operationTypes: ['update'],
    loader:         () => import('./archive_project_item'),
  },

  // ── lane definitions ─────────────────────────────────────────────────
  {
    name: 'list_lanes',
    description: 'List first-class Projects lane definitions. Keys are stable; display names are editable.',
    category: 'project',
    schemaDef: {
      scope: { type: 'enum', enum: ['global_default', 'project'], optional: true, description: 'Optional definition scope.' },
      project_id: { type: 'string', optional: true, description: 'Limit project-scoped definitions to one project.' },
      include_archived: { type: 'boolean', optional: true, description: 'Include archived lane definitions.' },
      include_reset: { type: 'boolean', optional: true, description: 'Include reset override audit rows.' },
    },
    operationTypes: ['read'],
    loader: () => import('./list_lanes'),
  },
  {
    name: 'resolve_lanes',
    description: 'Resolve the effective ordered lane set for a project with global, project_override, or project_only provenance.',
    category: 'project',
    schemaDef: {
      project_id: { type: 'string', description: 'Project whose inherited lane set should be resolved.' },
      include_archived: { type: 'boolean', optional: true, description: 'Include disabled or archived effective lanes.' },
    },
    operationTypes: ['read'],
    loader: () => import('./resolve_lanes'),
  },
  {
    name: 'create_lane',
    description: 'Create a global default, project override, or project-only lane. lane_key is immutable after creation.',
    category: 'project',
    schemaDef: {
      lane_key: { type: 'string', description: 'Stable machine key stored in work_tasks.status.' },
      display_name: { type: 'string', description: 'Editable user-facing lane name.' },
      scope: { type: 'enum', enum: ['global_default', 'project'], optional: true, description: 'Definition scope. Defaults to global_default.' },
      project_id: { type: 'string', optional: true, description: 'Required for project scope.' },
      base_lane_key: { type: 'string', optional: true, description: 'Inherited global key for an explicit project override.' },
      description: { type: 'string', optional: true, description: 'Lane purpose.' },
      color: { type: 'string', optional: true, description: 'Presentation color token.' },
      icon: { type: 'string', optional: true, description: 'Presentation icon token.' },
      position: { type: 'number', optional: true, description: 'Sort position.' },
      semantic_role: { type: 'enum', enum: ['backlog', 'planning', 'execution', 'review', 'blocked', 'terminal', 'manual'], optional: true, description: 'Behavioral role. Defaults to manual.' },
      enabled: { type: 'boolean', optional: true, description: 'Whether the lane is available.' },
      actor: { type: 'string', optional: true, description: 'Audit actor.' },
    },
    operationTypes: ['create'],
    loader: () => import('./create_lane'),
  },
  {
    name: 'update_lane',
    description: 'Update lane presentation, order, role, or re-enable it without changing its stable key. Use archive_lane to disable or remove a lane safely.',
    category: 'project',
    schemaDef: {
      id: { type: 'string', description: 'Lane definition id.' },
      display_name: { type: 'string', optional: true, description: 'New display name; never changes lane_key.' },
      description: { type: 'string', optional: true, description: 'New description.' },
      color: { type: 'string', optional: true, description: 'New color token; empty clears.' },
      icon: { type: 'string', optional: true, description: 'New icon token; empty clears.' },
      position: { type: 'number', optional: true, description: 'New sort position.' },
      semantic_role: { type: 'enum', enum: ['backlog', 'planning', 'execution', 'review', 'blocked', 'terminal', 'manual'], optional: true, description: 'New semantic role.' },
      enabled: { type: 'boolean', optional: true, description: 'Set true to enable the lane. Direct disabling is rejected; use archive_lane so populated lanes require an atomic destination move.' },
      actor: { type: 'string', optional: true, description: 'Audit actor.' },
    },
    operationTypes: ['update'],
    loader: () => import('./update_lane'),
  },
  {
    name: 'archive_lane',
    description: 'Archive a lane. A populated lane requires destination_lane_key and moves matching tasks atomically.',
    category: 'project',
    schemaDef: {
      id: { type: 'string', description: 'Lane definition id.' },
      destination_lane_key: { type: 'string', optional: true, description: 'Active destination key required when the lane contains tasks.' },
      actor: { type: 'string', optional: true, description: 'Audit actor.' },
    },
    operationTypes: ['update'],
    loader: () => import('./archive_lane'),
  },
  {
    name: 'restore_lane',
    description: 'Restore an archived lane definition in place.',
    category: 'project',
    schemaDef: {
      id: { type: 'string', description: 'Archived lane definition id.' },
      actor: { type: 'string', optional: true, description: 'Audit actor.' },
    },
    operationTypes: ['update'],
    loader: () => import('./restore_lane'),
  },
  {
    name: 'reorder_lanes',
    description: 'Atomically assign sequential positions to lane keys in one scope.',
    category: 'project',
    schemaDef: {
      scope: { type: 'enum', enum: ['global_default', 'project'], description: 'Scope being reordered.' },
      ordered_lane_keys: { type: 'array', items: { type: 'string' }, description: 'Lane keys in desired order.' },
      project_id: { type: 'string', optional: true, description: 'Required for project scope.' },
      actor: { type: 'string', optional: true, description: 'Audit actor.' },
    },
    operationTypes: ['update'],
    loader: () => import('./reorder_lanes'),
  },
  {
    name: 'reset_lane_override',
    description: 'Reset one project customization so the lane inherits its global definition again. The prior row remains as audit history.',
    category: 'project',
    schemaDef: {
      project_id: { type: 'string', description: 'Project owning the override.' },
      lane_key: { type: 'string', description: 'Stable lane key to reset.' },
      actor: { type: 'string', optional: true, description: 'Audit actor.' },
    },
    operationTypes: ['update'],
    loader: () => import('./reset_lane_override'),
  },
  {
    name: 'list_lane_workflow_bindings',
    description: 'List active or historical workflow bindings for Projects lanes.',
    category: 'project',
    schemaDef: {
      profile_id: { type: 'string', optional: true, description: 'Profile boundary; defaults to default.' },
      scope: { type: 'enum', enum: ['epic', 'project', 'global', 'core'], optional: true, description: 'Binding scope.' },
      epic_id: { type: 'string', optional: true, description: 'Filter by epic target.' },
      project_id: { type: 'string', optional: true, description: 'Filter by project target.' },
      lane_key: { type: 'string', optional: true, description: 'Filter by concrete lane key.' },
      semantic_role: { type: 'string', optional: true, description: 'Filter by semantic role.' },
      include_archived: { type: 'boolean', optional: true, description: 'Include superseded and removed bindings.' },
    },
    operationTypes: ['read'],
    loader: () => import('./list_lane_workflow_bindings'),
  },
  {
    name: 'set_lane_workflow_binding',
    description: 'Assign a compatible workflow to an epic, project, global, or protected-core lane scope.',
    category: 'project',
    schemaDef: {
      scope: { type: 'enum', enum: ['epic', 'project', 'global', 'core'], description: 'Binding scope.' },
      workflow_id: { type: 'string', description: 'Existing enabled workflow id.' },
      lane_key: { type: 'string', optional: true, description: 'Concrete lane key.' },
      semantic_role: { type: 'string', optional: true, description: 'Semantic lane role.' },
      epic_id: { type: 'string', optional: true, description: 'Required for epic scope.' },
      project_id: { type: 'string', optional: true, description: 'Required for project scope.' },
      profile_id: { type: 'string', optional: true, description: 'Profile boundary; defaults to default.' },
      actor: { type: 'string', optional: true, description: 'Audit actor.' },
    },
    operationTypes: ['update'],
    loader: () => import('./set_lane_workflow_binding'),
  },
  {
    name: 'remove_lane_workflow_binding',
    description: 'Soft-remove a custom lane workflow binding. Protected-core bindings cannot be removed.',
    category: 'project',
    schemaDef: {
      id: { type: 'string', description: 'Binding id.' },
      actor: { type: 'string', optional: true, description: 'Audit actor.' },
    },
    operationTypes: ['update'],
    loader: () => import('./remove_lane_workflow_binding'),
  },
  {
    name: 'resolve_lane_workflow',
    description: 'Resolve the effective lane workflow with precedence, compatibility, and visible fallback.',
    category: 'project',
    schemaDef: {
      task_id: { type: 'string', description: 'Task entering the lane.' },
      lane_key: { type: 'string', description: 'Destination lane key.' },
      profile_id: { type: 'string', optional: true, description: 'Profile boundary; defaults to default.' },
    },
    operationTypes: ['read'],
    loader: () => import('./resolve_lane_workflow'),
  },
  {
    name: 'inspect_lane_entry_automation',
    description: 'Inspect immutable lane-entry generations, workflow snapshots, execution ids, and outcomes for one task.',
    category: 'project',
    schemaDef: {
      task_id: { type: 'string', description: 'Task id.' },
    },
    operationTypes: ['read'],
    loader: () => import('./inspect_lane_entry_automation'),
  },
];
