import type { ToolManifest } from '../registry';

export const metaToolManifests: ToolManifest[] = [
  {
    name:        'upsert_conversation_keywords',
    description: 'Observer-only database writer for salient terms from the completed conversation turn. Canonicalizes and upserts terms by (term, thread_id), bumping hit_count and last_seen on repeats.',
    category:    'observation',
    schemaDef:   {
      terms:                    { type: 'array', description: 'Salient terms only (not stopwords, prose, or secrets); maximum 100.', items: { type: 'string' } },
      thread_id:                { type: 'string', description: 'Parent conversation thread id.' },
      conversation_history_id:  { type: 'string', optional: true, nullable: true, description: 'Parent conversation_history row id, when known.' },
      channel_id:               { type: 'string', optional: true, nullable: true, description: 'Parent channel id, when known.' },
      agent_id:                 { type: 'string', optional: true, nullable: true, description: 'Parent agent id, when known.' },
      source:                   { type: 'enum', optional: true, default: 'subconscious', enum: ['primary', 'subconscious', 'worker'], description: 'Writer source; use subconscious here.' },
    },
    operationTypes: ['create', 'update'],
    loader:         () => import('./upsert_conversation_keywords'),
  },
  {
    name:        'add_observational_memory',
    description: 'Use this tool to store the observations you make into long-term memory.',
    category:    'observation',
    schemaDef:   {
      id:       { type: 'string', optional: true, description: 'Existing observation ID to update in place. Omit to add a new observation or update a duplicate by content.' },
      priority: { type: 'string', optional: true, default: '🟡', description: 'Priority tag for this observation. Any short label works — common values: 🔴 / high, 🟡 / medium, ⚪ / low.' },
      content:  { type: 'string', description: 'One sentence only — extremely concise, always include the context' },
      source:   { type: 'string', optional: true, description: 'Optional source label for this observation.' },
    },
    operationTypes: ['create', 'read', 'update', 'delete'],
    loader:         () => import('./add_observational_memory'),
  },
  {
    name:        'exec',
    description: 'Run any shell command inside a fully isolated sandboxed Linux VM with root access. This is ALSO how you invoke every `sulla <category>/<tool>` CLI command surfaced by browse_tools — pass the full `sulla ...` command string as the `command` arg (e.g. command: "sulla github/create_issue \'{\\"title\\":\\"bug\\"}\'"). Safe to install packages, compile code, delete files, or run any system command.',
    category:    'meta',
    schemaDef:   {
      command: { type: 'string', optional: true, description: 'The exact shell command to run' },
      cmd:     { type: 'string', optional: true, description: 'Alias for command' },
      cwd:     { type: 'string', optional: true, description: 'Working directory inside the VM to run the command in' },
      timeout: { type: 'number', optional: true, description: 'Timeout in milliseconds (default 120000). Use higher values for long-running installs.' },
      stdin:   { type: 'string', optional: true, description: 'Optional stdin data to pipe into the command' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./exec'),
  },
  {
    name:        'exechost',
    description: 'LAST RESORT host shell — runs a command on the HOST macOS machine, NOT the Lima VM. Default to regular exec (VM sandbox) for everyday work; home files are already mounted into the VM. Use exechost ONLY when the parent host MUST be used (host-only binaries/GUI apps, host Docker Desktop, tools unavailable in the VM, or explicit user request). Uses the user\'s login shell (/bin/zsh or /bin/bash) so PATH includes Homebrew/nvm/rbenv. Silent output, no Terminal window. Requires "Allow access to the host machine" in Preferences → Application → Administrative Access. Prefer this over AppleScript→Terminal when host execution is truly required.',
    category:    'meta',
    schemaDef:   {
      command: { type: 'string', optional: true, description: 'The exact shell command to run on the host' },
      cmd:     { type: 'string', optional: true, description: 'Alias for command' },
      cwd:     { type: 'string', optional: true, description: 'Working directory on the host to run the command in (absolute path)' },
      timeout: { type: 'number', optional: true, description: 'Timeout in milliseconds (default 60000)' },
      stdin:   { type: 'string', optional: true, description: 'Optional stdin data to pipe into the command' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./exechost'),
  },
  {
    name:        'remove_observational_memory',
    description: 'Archive (soft-delete) a specific observational memory by its ID. The record is never hard-deleted — it is marked archived=true so the history is always recoverable.',
    category:    'observation',
    schemaDef:   {
      id: { type: 'string', description: 'The 4-character ID of the observation to archive.' },
    },
    operationTypes: ['delete'],
    loader:         () => import('./remove_observational_memory'),
  },
  {
    name:        'search_observations',
    description: 'Search active observational memories by keyword or phrase. The query is split into words and any observation containing ANY meaningful word matches (stopwords ignored), ranked by phrase hit then word-match count. Returns compact rows (id, priority, timestamp, content). Use this before adding a new observation to check for existing similar ones.',
    category:    'observation',
    schemaDef:   {
      query:            { type: 'string', description: 'Search keyword or phrase — split into words, any-word ILIKE match against observation content.' },
      limit:            { type: 'number', optional: true, description: 'Max results to return (default 20).' },
      include_archived: { type: 'boolean', optional: true, description: 'When true, also searches archived (soft-deleted) observations (default false).' },
    },
    operationTypes: ['read'],
    loader:         () => import('./search_observations'),
  },
  {
    name:        'list_observations',
    description: 'List active observational memories sorted by priority (critical/high first) then recency. Optionally filter by priority level.',
    category:    'observation',
    schemaDef:   {
      priority:         { type: 'string', optional: true, description: 'Priority filter — e.g. "critical", "high", "medium", "low". Omit to list all.' },
      limit:            { type: 'number', optional: true, description: 'Max results to return (default 50).' },
      include_archived: { type: 'boolean', optional: true, description: 'When true, also includes archived observations (default false).' },
    },
    operationTypes: ['read'],
    loader:         () => import('./list_observations'),
  },
  {
    name:        'add_identity_observation',
    description: 'Store a focused identity observation into the domain-keyed identity_observations table (human / business / world / agent / environment / projects — mirrors ~/sulla/identity/). Levels are CERTAINTY: 3 = stated fact (subject directly told us), 2 = derived fact (established from conversation evidence), 1 = conclusion (reasoned from L3/L2 facts — personality, style, habits). Pass an existing id to update in place; otherwise a substantially similar active row in the same domain is updated instead of duplicated.',
    category:    'observation',
    schemaDef:   {
      id:       { type: 'string', optional: true, description: 'Existing observation ID to update in place. Omit to add a new observation or update a duplicate by content.' },
      domain:   { type: 'string', optional: true, description: 'Identity domain: human, business, world, agent, environment, or projects (default human).' },
      level:    { type: 'number', description: 'Certainty level: 3 = stated fact, 2 = derived fact, 1 = conclusion.' },
      category: { type: 'string', optional: true, description: 'Focus category — e.g. identity, relationship, association, personality, habit, preference, goal.' },
      content:  { type: 'string', description: 'One sentence only — extremely concise, always include the context.' },
      basis:    { type: 'string', optional: true, description: 'For L2/L1: what stated facts or evidence this was derived or concluded from.' },
      subject:  { type: 'string', optional: true, description: 'Optional structured subject, currently used by the agent/self domain: agent or agent.user.' },
      evidence: { type: 'string', optional: true, description: 'Optional quote or turn reference supporting the observation.' },
      confidence: { type: 'number', optional: true, description: 'Optional confidence score from 0 to 1.' },
      kind:     { type: 'string', optional: true, description: 'Optional self-observation kind: correction, constraint, method, commitment, or preference.' },
      source:   { type: 'string', optional: true, description: 'Optional source label for this observation.' },
    },
    operationTypes: ['create', 'read', 'update'],
    loader:         () => import('./add_identity_observation'),
  },
  {
    name:        'remove_identity_observation',
    description: 'Archive (soft-delete) an identity observation by its ID. The record is never hard-deleted — it is marked archived=true so the history is always recoverable.',
    category:    'observation',
    schemaDef:   {
      id: { type: 'string', description: 'The 4-character ID of the identity observation to archive.' },
    },
    operationTypes: ['delete'],
    loader:         () => import('./remove_identity_observation'),
  },
  {
    name:        'search_identity_observations',
    description: 'Search active identity observations within one domain (human / business / world / agent / environment / projects) by keyword or phrase. Any-word ILIKE match ranked by phrase hit, word-match count, then certainty level (stated facts first) and recency. Use this before adding a new identity observation to check for existing similar ones.',
    category:    'observation',
    schemaDef:   {
      query:            { type: 'string', description: 'Search keyword or phrase — split into words, any-word ILIKE match against observation content.' },
      domain:           { type: 'string', optional: true, description: 'Identity domain to search: human, business, world, agent, environment, or projects (default human).' },
      limit:            { type: 'number', optional: true, description: 'Max results to return (default 20).' },
      include_archived: { type: 'boolean', optional: true, description: 'When true, also searches archived (soft-deleted) rows (default false).' },
    },
    operationTypes: ['read'],
    loader:         () => import('./search_identity_observations'),
  },
  {
    name:        'list_identity_observations',
    description: 'List active identity observations for one domain, most certain first (L3 stated → L2 derived → L1 concluded) then most recent. Optionally filter by level and/or category.',
    category:    'observation',
    schemaDef:   {
      domain:   { type: 'string', optional: true, description: 'Identity domain: human, business, world, agent, environment, or projects (default human).' },
      level:    { type: 'number', optional: true, description: 'Certainty level filter: 3, 2, or 1. Omit to list all levels.' },
      category: { type: 'string', optional: true, description: 'Category filter — e.g. identity, relationship, personality, habit. Omit to list all.' },
      limit:    { type: 'number', optional: true, description: 'Max results to return (default 50).' },
    },
    operationTypes: ['read'],
    loader:         () => import('./list_identity_observations'),
  },
  {
    name:        'update_identity_section',
    description: 'Write the consolidated identity profile for a domain into its system-prompt section (e.g. the "user" section injected into every system prompt). Overwrites the section content and marks it customized so the boot seeder never clobbers it. Used by the nightly "dreaming" consolidation routines; DB-only, no filesystem.',
    category:    'observation',
    schemaDef:   {
      id:      { type: 'string', description: 'System-prompt section id to write — the consolidated identity slot for a domain (e.g. "user").' },
      content: { type: 'string', description: 'The consolidated profile text to store as the section content.' },
    },
    operationTypes: ['update'],
    loader:         () => import('./update_identity_section'),
  },
  {
    name:        'ask_user_question',
    description: 'Pause and ask the user one or more multiple-choice questions, then BLOCK until they answer in the chat (or the timeout elapses — default 5 min). Renders an interactive card with selectable options; the user may also type a free-form answer. Returns the selected option(s) per question. Use whenever the next step depends on a decision only the user can make — picking between approaches, confirming an assumption, supplying a missing detail, or getting a yes/no go-ahead (offer Approve / Deny options).',
    category:    'meta',
    schemaDef:   {
      questions: {
        type:        'array',
        description: '1–4 questions to ask. Each renders as its own card with selectable options.',
        items:       {
          type:       'object',
          properties: {
            question:    { type: 'string', description: 'The full question text shown to the user.' },
            header:      { type: 'string', description: 'Short label/chip shown above the question (≤ ~12 chars), e.g. "Auth method".' },
            multiSelect: { type: 'boolean', description: 'Set true to let the user pick multiple options. Default false (single choice).' },
            options:     {
              type:        'array',
              description: '2–4 distinct options the user can choose from.',
              items:       {
                type:       'object',
                properties: {
                  label:       { type: 'string', description: 'The option text the user selects.' },
                  description: { type: 'string', description: 'Optional one-line explanation of what this option means or implies.' },
                },
              },
            },
          },
        },
      },
      timeoutMs: { type: 'number', optional: true, description: 'Timeout in ms (min 5000, max 1800000, default 300000 = 5 min). On timeout resolves with no selection.' },
    },
    operationTypes: ['read'],
    loader:         () => import('./ask_user_question'),
  },
  {
    name:        'file_search',
    description: 'Fast full-text keyword search (BM25-ranked) across any directory PLUS the bundled sulla-docs (agent + tool reference) by default. Faster than find or grep for multi-word queries — use this as your default search tool. Matches file contents and filenames. Small directories are live-scanned (always fresh); large ones use an incremental on-disk index built automatically, with coverage reported when partial. Pass includeSullaDocs:false to skip the sulla-docs second pass.',
    category:    'meta',
    schemaDef:   {
      query:            { type: 'string', description: 'Search query — keywords, concepts, or questions to match against file contents and names.' },
      dirPath:          { type: 'string', optional: true, description: 'Absolute path to the primary directory to search in. Defaults to the user home directory.' },
      limit:            { type: 'number', optional: true, description: 'Maximum number of results to return per directory (default 20).' },
      reindex:          { type: 'boolean', optional: true, description: 'Force re-index the directory(ies) before searching.' },
      includeSullaDocs: { type: 'boolean', optional: true, description: 'Whether to also search the bundled sulla-docs/ reference (default true). Set false to limit search to dirPath only.' },
    },
    operationTypes: ['read'],
    loader:         () => import('./meta_search'),
  },
  {
    name:        'read_file',
    description: 'Read the contents of a file with optional line range. Returns line-numbered content and the total line count. Can also list directory contents.',
    category:    'meta',
    schemaDef:   {
      path:      { type: 'string', description: 'Path to the file to read. Supports ~ for home directory.' },
      startLine: { type: 'number', optional: true, description: 'First line to read (1-indexed). Defaults to 1.' },
      endLine:   { type: 'number', optional: true, description: 'Last line to read (1-indexed). Defaults to end of file.' },
    },
    operationTypes: ['read'],
    loader:         () => import('./read_file'),
  },
  {
    name:        'write_file',
    description: 'Write or overwrite file contents. Creates parent directories if needed. Restricted to the home directory.',
    category:    'observation',
    schemaDef:   {
      path:    { type: 'string', description: 'Path to the file to write. Supports ~ for home directory.' },
      content: { type: 'string', description: 'The full content to write to the file.' },
    },
    operationTypes: ['create', 'update'],
    loader:         () => import('./write_file'),
  },
  {
    name:        'recall_index_lookup',
    description: 'Check the Redis citation index for previously-researched digests BEFORE re-reading files or re-searching directories. Pass a topic and/or a list of file paths. Returns trusted digests for files verified unchanged (cheap content-hash check), drops stale entries automatically, and lists which paths/topics need fresh research.',
    category:    'memory',
    schemaDef:   {
      topic: { type: 'string', optional: true, description: 'Topic to look up (e.g. the subject of the user request — "github push auth", "sulla-mobile project"). Normalized internally.' },
      paths: { type: 'array', items: { type: 'string' }, optional: true, description: 'File paths to check for cached digests (e.g. SKILL.md or PROJECT.md paths you would otherwise read).' },
    },
    operationTypes: ['read'],
    loader:         () => import('./recall_index_lookup'),
  },
  {
    name:        'recall_index_store',
    description: 'Persist freshly-researched citation digests into the Redis citation index so future recall passes can reuse them without re-reading source files. Store one entry per file you read (path + the digest you produced), and optionally a topic with citation strings. Entries are verified against file content hashes and expire after 24h unless re-hit.',
    category:    'memory',
    schemaDef:   {
      files: {
        type:        'array',
        optional:    true,
        description: 'Array of {path, digest} objects — one per source file researched. The digest should be the full trusted-citation block produced for that file.',
        items:       {
          type:       'object',
          properties: {
            path:   { type: 'string', description: 'Path of the source file the digest cites.' },
            digest: { type: 'string', description: 'The trusted-citation digest for this file.' },
          },
        },
      },
      topic:     { type: 'string', optional: true, description: 'Topic to file these citations under for future topic lookups.' },
      citations: { type: 'array', items: { type: 'string' }, optional: true, description: 'Citation strings to store under the topic. Required when topic is set.' },
    },
    operationTypes: ['create', 'update'],
    loader:         () => import('./recall_index_store'),
  },
  {
    name:        'recall_conversations',
    description: 'Search and read the on-disk conversation logs (~/sulla/logs/conv_*.jsonl) — the training-formatted JSONL transcripts of every past user-facing conversation (subconscious agents are never logged here). Unlike search_conversations (which matches DB titles/summaries), this searches the actual message CONTENT and returns transcripts. action:"search" finds past conversations by keyword and returns each hit\'s id, date, title, and a matching snippet; action:"read" renders one conversation\'s full transcript by id. Use this to recall what was actually said/decided in earlier conversations.',
    category:    'memory',
    schemaDef:   {
      action: { type: 'enum', enum: ['search', 'read'], description: 'search: keyword content-search across all conversation logs. read: render one conversation transcript by id.' },
      query:  { type: 'string', optional: true, description: 'Keywords to match against message content. Required for search.' },
      id:     { type: 'string', optional: true, description: 'Conversation id (from a search result). Required for read.' },
      limit:  { type: 'number', optional: true, description: 'Max search results to return (default 8, max 20).' },
    },
    operationTypes: ['read'],
    loader:         () => import('./recall_conversations'),
  },
  {
    name:        'browse_tools',
    description: 'Discover available sulla CLI tools by category or keyword. Returns ready-to-run `sulla <category>/<tool>` commands with descriptions and parameter JSON. IMPORTANT: the commands it returns are NOT directly callable tools — you invoke each one by passing the full command string to the `exec` tool (e.g. exec({command: "sulla docker/ps \'{}\'"})). NEVER call execute_workflow for any command listed here — execute_workflow is only for named n8n/Sulla workflows. Call this before attempting any sulla CLI invocation you are unsure about.',
    category:    'meta',
    schemaDef:   {
      category: { type: 'string', optional: true, description: 'Tool category to list (e.g. docker, github, slack, redis, pg, playwright, calendar, n8n, kubectl, lima, chrome, vault, extensions, rdctl, meta, agents, skills, bridge).' },
      query:    { type: 'string', optional: true, description: 'Keyword to search tool names and descriptions across all categories.' },
    },
    operationTypes: ['read'],
    loader:         () => import('./browse_tools'),
  },
];
