/**
 * Compact word list for passphrase generation.
 * Based on the EFF short word list — common, easy-to-type English words.
 * ~1300 words provides ~10.3 bits of entropy per word.
 */
export const WORDLIST: string[] = [
  'able', 'acid', 'aged', 'also', 'area', 'army', 'away', 'baby', 'back', 'ball',
  'band', 'bank', 'base', 'bath', 'bear', 'beat', 'been', 'bell', 'belt', 'best',
  'bill', 'bird', 'bite', 'blow', 'blue', 'boat', 'body', 'bomb', 'bond', 'bone',
  'book', 'boot', 'born', 'boss', 'both', 'bowl', 'bulk', 'burn', 'bush', 'busy',
  'buzz', 'cafe', 'cage', 'cake', 'call', 'calm', 'came', 'camp', 'card', 'care',
  'cart', 'case', 'cash', 'cast', 'cave', 'cell', 'chat', 'chef', 'chip', 'chop',
  'city', 'clad', 'claim', 'clam', 'clap', 'clay', 'clip', 'club', 'clue', 'coal',
  'coat', 'code', 'coil', 'coin', 'cold', 'colt', 'come', 'cook', 'cool', 'cope',
  'copy', 'cord', 'core', 'corn', 'cost', 'coup', 'crew', 'crop', 'crow', 'cure',
  'curl', 'cute', 'dale', 'dame', 'damp', 'dare', 'dark', 'dart', 'dash', 'data',
  'dawn', 'dead', 'deaf', 'deal', 'dear', 'debt', 'deck', 'deed', 'deem', 'deep',
  'deer', 'demo', 'deny', 'desk', 'dial', 'dice', 'diet', 'dirt', 'disc', 'dish',
  'dock', 'does', 'dome', 'done', 'doom', 'door', 'dose', 'down', 'draw', 'drew',
  'drip', 'drop', 'drum', 'dual', 'duel', 'duke', 'dull', 'dune', 'dusk', 'dust',
  'duty', 'each', 'earl', 'earn', 'ease', 'east', 'easy', 'edge', 'else', 'emit',
  'epic', 'even', 'ever', 'evil', 'exam', 'exit', 'face', 'fact', 'fade', 'fail',
  'fair', 'fake', 'fall', 'fame', 'fang', 'fare', 'farm', 'fast', 'fate', 'fawn',
  'fear', 'feat', 'feed', 'feel', 'feet', 'fell', 'felt', 'file', 'fill', 'film',
  'find', 'fine', 'fire', 'firm', 'fish', 'fist', 'flag', 'flame', 'flap', 'flat',
  'flaw', 'fled', 'flee', 'flew', 'flip', 'flock', 'flow', 'foam', 'fold', 'folk',
  'fond', 'font', 'food', 'fool', 'foot', 'ford', 'fork', 'form', 'fort', 'foul',
  'four', 'free', 'frog', 'from', 'fuel', 'full', 'fund', 'fury', 'fuse', 'gale',
  'game', 'gang', 'gate', 'gave', 'gaze', 'gear', 'gene', 'gift', 'gild', 'girl',
  'give', 'glad', 'glow', 'glue', 'goat', 'goes', 'gold', 'golf', 'gone', 'good',
  'grab', 'gram', 'gray', 'grew', 'grey', 'grid', 'grim', 'grin', 'grip', 'grow',
  'gulf', 'gust', 'hack', 'hair', 'half', 'hall', 'halt', 'hand', 'hang', 'harm',
  'harp', 'hate', 'haul', 'have', 'hawk', 'haze', 'head', 'heal', 'heap', 'hear',
  'heat', 'heel', 'held', 'help', 'herb', 'herd', 'here', 'hero', 'hide', 'high',
  'hike', 'hill', 'hint', 'hire', 'hold', 'hole', 'home', 'hook', 'hope', 'horn',
  'host', 'hour', 'huge', 'hull', 'hung', 'hunt', 'hurt', 'hymn', 'icon', 'idea',
  'inch', 'info', 'into', 'iron', 'isle', 'item', 'jack', 'jade', 'jail', 'jazz',
  'jean', 'jest', 'jewel', 'join', 'joke', 'jump', 'jury', 'just', 'keen', 'keep',
  'kelp', 'kept', 'kick', 'kill', 'kind', 'king', 'kiss', 'kite', 'knee', 'knew',
  'knit', 'knob', 'knot', 'know', 'lace', 'lack', 'laid', 'lake', 'lamb', 'lamp',
  'land', 'lane', 'lark', 'last', 'late', 'lawn', 'lead', 'leaf', 'leak', 'lean',
  'leap', 'left', 'lend', 'lens', 'lent', 'less', 'lied', 'life', 'lift', 'like',
  'limb', 'lime', 'limp', 'line', 'link', 'lion', 'list', 'live', 'load', 'loaf',
  'loan', 'lock', 'loft', 'logo', 'lone', 'long', 'look', 'loop', 'lord', 'lore',
  'lose', 'loss', 'lost', 'loud', 'love', 'luck', 'lump', 'lung', 'lure', 'lurk',
  'lush', 'made', 'mail', 'main', 'make', 'male', 'mall', 'malt', 'mane', 'many',
  'mare', 'mark', 'mars', 'mask', 'mass', 'mast', 'mate', 'maze', 'meal', 'mean',
  'meat', 'meet', 'meld', 'melt', 'memo', 'mend', 'menu', 'mere', 'mesh', 'mild',
  'mile', 'milk', 'mill', 'mime', 'mind', 'mine', 'mint', 'miss', 'mist', 'mitt',
  'moat', 'mock', 'mode', 'mold', 'monk', 'mood', 'moon', 'moor', 'more', 'moss',
  'most', 'moth', 'move', 'much', 'mule', 'muse', 'mush', 'must', 'myth', 'nail',
  'name', 'navy', 'near', 'neat', 'neck', 'need', 'nest', 'news', 'next', 'nice',
  'nine', 'node', 'none', 'norm', 'nose', 'note', 'noun', 'nude', 'nuts', 'oath',
  'obey', 'odds', 'ogre', 'okay', 'omen', 'once', 'only', 'onto', 'opal', 'open',
  'oral', 'orbs', 'orca', 'oven', 'over', 'owed', 'oxen', 'pace', 'pack', 'page',
  'paid', 'pail', 'pain', 'pair', 'pale', 'palm', 'pane', 'park', 'part', 'pass',
  'past', 'path', 'peak', 'pear', 'peel', 'peer', 'pelt', 'perk', 'pest', 'pick',
  'pier', 'pile', 'pine', 'pink', 'pipe', 'pith', 'plan', 'play', 'plea', 'plot',
  'plow', 'plug', 'plum', 'plus', 'poem', 'poet', 'pole', 'poll', 'polo', 'pond',
  'pool', 'poor', 'pope', 'pork', 'port', 'pose', 'post', 'pour', 'pray', 'prey',
  'prop', 'pull', 'pulp', 'pump', 'pure', 'push', 'quay', 'quit', 'quiz', 'race',
  'rack', 'raft', 'rage', 'raid', 'rail', 'rain', 'ramp', 'rang', 'rank', 'rare',
  'rash', 'rate', 'rave', 'read', 'real', 'reap', 'rear', 'reed', 'reef', 'reel',
  'rely', 'rent', 'rest', 'rich', 'ride', 'rift', 'rind', 'ring', 'riot', 'rise',
  'risk', 'road', 'roam', 'roar', 'robe', 'rock', 'rode', 'role', 'roll', 'roof',
  'room', 'root', 'rope', 'rose', 'rove', 'rude', 'ruin', 'rule', 'rung', 'rush',
  'rust', 'ruth', 'sack', 'safe', 'sage', 'said', 'sail', 'sake', 'sale', 'salt',
  'same', 'sand', 'sang', 'sane', 'sank', 'save', 'scar', 'seal', 'seam', 'seat',
  'seed', 'seek', 'seem', 'seen', 'self', 'sell', 'send', 'sent', 'sept', 'shed',
  'shin', 'ship', 'shoe', 'shop', 'shot', 'show', 'shut', 'sick', 'side', 'sift',
  'sigh', 'sign', 'silk', 'sill', 'sing', 'sink', 'site', 'size', 'skim', 'skin',
  'skip', 'slab', 'slam', 'slap', 'slat', 'sled', 'slew', 'slid', 'slim', 'slip',
  'slit', 'slot', 'slow', 'slug', 'snap', 'snow', 'soak', 'soap', 'soar', 'sock',
  'soft', 'soil', 'sold', 'sole', 'some', 'song', 'soon', 'sore', 'sort', 'soul',
  'sour', 'span', 'spar', 'spec', 'sped', 'spin', 'spit', 'spot', 'spur', 'star',
  'stay', 'stem', 'step', 'stew', 'stir', 'stop', 'stow', 'stub', 'stud', 'such',
  'suit', 'sulk', 'sung', 'sunk', 'sure', 'surf', 'swan', 'swap', 'swim', 'swop',
  'swum', 'sync', 'tabs', 'tack', 'tact', 'tail', 'take', 'tale', 'talk', 'tall',
  'tame', 'tank', 'tape', 'taps', 'tarn', 'task', 'taxi', 'teak', 'teal', 'team',
  'tear', 'tech', 'tell', 'temp', 'tend', 'tent', 'term', 'test', 'text', 'than',
  'that', 'them', 'then', 'they', 'thin', 'this', 'thorn', 'tick', 'tide', 'tidy',
  'tied', 'tier', 'tile', 'till', 'tilt', 'time', 'tint', 'tiny', 'tire', 'toad',
  'toga', 'toil', 'told', 'toll', 'tomb', 'tone', 'took', 'tool', 'tops', 'tore',
  'torn', 'toss', 'tour', 'town', 'trap', 'tray', 'tree', 'trek', 'trim', 'trio',
  'trip', 'trod', 'trot', 'true', 'tube', 'tuck', 'tuna', 'tune', 'turf', 'turn',
  'tusk', 'tutu', 'twin', 'type', 'ugly', 'undo', 'unit', 'unto', 'upon', 'urge',
  'used', 'user', 'vain', 'vale', 'vane', 'vary', 'vase', 'vast', 'veil', 'vein',
  'vent', 'verb', 'very', 'vest', 'veto', 'vial', 'vice', 'view', 'vine', 'visa',
  'void', 'volt', 'vote', 'wade', 'wage', 'wait', 'wake', 'walk', 'wall', 'wand',
  'want', 'ward', 'warm', 'warn', 'warp', 'wary', 'wash', 'wasp', 'wave', 'wavy',
  'waxy', 'weak', 'wear', 'weed', 'week', 'well', 'welt', 'went', 'wept', 'were',
  'west', 'what', 'when', 'whom', 'wide', 'wife', 'wild', 'will', 'wilt', 'wily',
  'wimp', 'wind', 'wine', 'wing', 'wink', 'wipe', 'wire', 'wise', 'wish', 'with',
  'woke', 'wolf', 'wood', 'wool', 'word', 'wore', 'work', 'worm', 'worn', 'wove',
  'wrap', 'wren', 'yank', 'yard', 'yarn', 'year', 'yell', 'yoga', 'yoke', 'your',
  'zeal', 'zero', 'zinc', 'zone', 'zoom',
];

/** Returns a cryptographically random integer in [0, max) */
export function secureRandomInt(max: number): number {
  const array = new Uint32Array(1);
  (globalThis.crypto || require('crypto').webcrypto).getRandomValues(array);
  return array[0] % max;
}

/** Pick a random word from the list */
export function randomWord(): string {
  return WORDLIST[secureRandomInt(WORDLIST.length)];
}
