import type { ToolManifest } from '../registry';

export const playwrightToolManifests: ToolManifest[] = [
  {
    name:        'browser_tab',
    description: 'Open, navigate, or close browser tabs. Returns a dehydrated DOM tree showing page structure and interactive elements. Reuse the same assetId to navigate an existing tab to a new URL. IMPORTANT: Before doing any web research or multi-page browsing, load the web-research-playwright skill first — it contains essential patterns for fast multi-step workflows using exec_in_page + __sulla helpers.',
    category:    'playwright',
    schemaDef:   {
      action:    { type: 'enum', enum: ['upsert', 'remove'], default: 'upsert', description: 'upsert creates/updates an asset; remove deletes by assetId.' },
      assetType: { type: 'enum', optional: true, enum: ['iframe', 'document'], description: 'Required for upsert.' },
      assetId:   { type: 'string', optional: true, description: 'Stable asset ID. Reuse the same ID to update an existing tab.' },
      skillSlug: { type: 'string', optional: true, description: 'Optional skill slug to associate with the asset.' },
      title:     { type: 'string', optional: true },
      url:       { type: 'string', optional: true, description: 'Required for iframe upsert.' },
      content:   { type: 'string', optional: true, description: 'Document HTML/markdown content.' },
      active:    { type: 'boolean', optional: true, default: true },
      collapsed: { type: 'boolean', optional: true, default: true },
      refKey:    { type: 'string', optional: true },
    },
    operationTypes: ['create', 'update', 'delete'],
    loader:         () => import('./browser_tab'),
  },
  {
    name:        'click_element',
    description: 'Click a button, link, or interactive element on a website asset. If the click causes navigation, automatically waits for the new page to load and returns the full page state (title, URL, elements, content). Use handles from get_page_snapshot (e.g. @btn-save, @link-home) or a CSS selector. Omit assetId to target the active asset.',
    category:    'playwright',
    schemaDef:   {
      handle:  { type: 'string', description: 'The element handle (@btn-<slug>, @link-<slug>, data-test-id, or CSS selector)' },
      assetId: { type: 'string', optional: true, description: 'Target asset ID (omit for the currently active website)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./click_element'),
  },
  {
    name:        'get_form_values',
    description: 'Get a map of all visible form field values (inputs, textareas, selects) from a website asset. Omit assetId to target the active asset.',
    category:    'playwright',
    schemaDef:   {
      assetId: { type: 'string', optional: true, description: 'Target asset ID (omit for the currently active website)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./get_form_values'),
  },
  {
    name:        'get_page_snapshot',
    description: 'Get page state. In "full" mode (default): title, URL, interactive elements (buttons, links, forms with handles), reader-mode content, and scroll position. In "dehydrated" mode: compressed DOM tree (~5k tokens) for quick action planning. Omit assetId to target the active asset.',
    category:    'playwright',
    schemaDef:   {
      assetId: { type: 'string', optional: true, description: 'Target asset ID (omit for the currently active website)' },
      mode:    { type: 'enum', optional: true, enum: ['full', 'dehydrated'], description: 'full returns complete page with content. dehydrated returns compressed DOM tree (~5k tokens) for action planning. Default: full' },
    },
    operationTypes: ['read'],
    loader:         () => import('./get_page_snapshot'),
  },
  {
    name:        'get_page_text',
    description: 'Get the readable text content of a website asset with title, URL, and scroll position. Uses reader-mode extraction (strips nav, ads, boilerplate) with fallback to raw text. Omit assetId to target the active asset.',
    category:    'playwright',
    schemaDef:   {
      assetId: { type: 'string', optional: true, description: 'Target asset ID (omit for the currently active website)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./get_page_text'),
  },
  {
    name:        'scroll_to_element',
    description: 'Scroll a matching element into view on a website asset using a CSS selector. Omit assetId to target the active asset.',
    category:    'playwright',
    schemaDef:   {
      selector: { type: 'string', description: 'CSS selector of the element to scroll into view' },
      assetId:  { type: 'string', optional: true, description: 'Target asset ID (omit for the currently active website)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./scroll_to_element'),
  },
  {
    name:        'press_key',
    description: 'Press a key on a website asset. Use for form submission (Enter), closing dialogs (Escape), navigating dropdowns (ArrowDown/ArrowUp), or tabbing between fields (Tab). Specify a handle to target a specific element, or omit to press on the currently focused element.',
    category:    'playwright',
    schemaDef:   {
      key:     { type: 'string', description: 'Key to press: Enter, Escape, Tab, ArrowDown, ArrowUp, ArrowLeft, ArrowRight, Backspace, Space' },
      handle:  { type: 'string', optional: true, description: 'Element handle (@field-q, @btn-search) or CSS selector. Omit to target the focused element.' },
      assetId: { type: 'string', optional: true, description: 'Target asset ID (omit for the currently active website)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./press_key'),
  },
  {
    name:        'set_field',
    description: 'Set the value of a form field (input, textarea, select) on a website asset. If submit is true, presses Enter after setting the value to submit the form. If the change triggers navigation (e.g. form auto-submit), returns the full new page state. Use handles from get_page_snapshot (e.g. @field-email, @field-username). Omit assetId to target the active asset.',
    category:    'playwright',
    schemaDef:   {
      handle:  { type: 'string', description: 'The field handle (@field-<id|name>) or element id/name' },
      value:   { type: 'string', description: 'The value to set' },
      submit:  { type: 'boolean', optional: true, description: 'Press Enter after setting the value to submit the form. Defaults to false.' },
      assetId: { type: 'string', optional: true, description: 'Target asset ID (omit for the currently active website)' },
    },
    operationTypes: ['update'],
    loader:         () => import('./set_field'),
  },
  {
    name:        'wait_for_element',
    description: 'Wait for a CSS selector to become visible on a website asset. Useful after clicking a button to wait for new content to appear. Omit assetId to target the active asset.',
    category:    'playwright',
    schemaDef:   {
      selector: { type: 'string', description: 'CSS selector to wait for' },
      timeout:  { type: 'number', optional: true, default: 5000, description: 'Maximum time to wait in milliseconds (default 5000)' },
      assetId:  { type: 'string', optional: true, description: 'Target asset ID (omit for the currently active website)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./wait_for_element'),
  },
  {
    name:        'browse_page',
    description: 'Browse and read web page content with smart extraction. Actions: "read" returns Readability-enhanced content (shows diff if page was read before); "scroll_down"/"scroll_up" scrolls and returns only NEW content; "scroll_to_top" resets; "search" finds text with context and highlights matches in the browser; "chunks" returns a table of contents; "chunk" returns a specific section by ID. Use this tool for research, reading articles, and navigating long pages.',
    category:    'playwright',
    schemaDef:   {
      action:   { type: 'enum', enum: ['read', 'scroll_down', 'scroll_up', 'scroll_to_top', 'search', 'chunks', 'chunk'], description: 'What to do: read, scroll, search, or navigate by section' },
      query:    { type: 'string', optional: true, description: 'Search query (required when action is "search")' },
      chunk_id: { type: 'number', optional: true, description: 'Section ID to read (required when action is "chunk")' },
      assetId:  { type: 'string', optional: true, description: 'Target asset ID (omit for the currently active website)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./browse_page'),
  },
  {
    name:        'synthesize_tabs',
    description: 'Extract and combine reader-mode content from multiple open browser tabs into a single response with source attribution. Useful for cross-page research: comparing information, aggregating data from multiple sources, or building summaries from several references. Omit assetIds to synthesize all open tabs.',
    category:    'playwright',
    schemaDef:   {
      assetIds:  { type: 'string', optional: true, description: 'Comma-separated asset IDs to synthesize (omit for all open tabs)' },
      max_chars: { type: 'number', optional: true, description: 'Max characters per tab (default 4000)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./synthesize_tabs'),
  },
  {
    name:        'list_tabs',
    description: 'List all open browser tabs with their assetId, URL, title, and status (ready/loading). Use to see what tabs are open before interacting.',
    category:    'playwright',
    schemaDef:   {},
    operationTypes: ['read'],
    loader:         () => import('./list_tabs'),
  },

  // ── Visual / Computer Use tools ─────────────────────────────────────

  {
    name:        'take_screenshot',
    description: 'Capture a visual screenshot of a website tab. Returns the image so you can SEE the page. By default includes a coordinate grid overlay so you know exact pixel positions for click_at/type_at. Set annotate to true to also draw numbered boxes on interactive elements.',
    category:    'playwright',
    schemaDef:   {
      assetId:  { type: 'string', optional: true, description: 'Target tab (omit for the active tab)' },
      grid:     { type: 'boolean', optional: true, description: 'Show coordinate grid overlay (default true)' },
      annotate: { type: 'boolean', optional: true, description: 'Draw numbered boxes on interactive elements (default false)' },
    },
    operationTypes: ['read'],
    loader:         () => import('./screenshot'),
  },
  {
    name:        'click_at',
    description: 'Click at pixel coordinates on a website tab using trusted mouse events. Use take_screenshot first to identify coordinates. After clicking, automatically captures a screenshot so you can see the result. Useful for elements that DOM handles cannot reach.',
    category:    'playwright',
    schemaDef:   {
      x:            { type: 'number', description: 'X coordinate in pixels' },
      y:            { type: 'number', description: 'Y coordinate in pixels' },
      button:       { type: 'enum', optional: true, enum: ['left', 'right', 'middle'], description: 'Mouse button (default left)' },
      double_click: { type: 'boolean', optional: true, description: 'Double-click instead of single click' },
      assetId:      { type: 'string', optional: true, description: 'Target tab (omit for the active tab)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./click_coordinates'),
  },
  {
    name:        'type_at',
    description: 'Click at coordinates to focus an element, then type text using trusted keyboard events. After typing, captures a screenshot. Set submit to true to press Enter after typing. Use for chat widgets, search boxes, or any input that DOM-based set_field cannot reach.',
    category:    'playwright',
    schemaDef:   {
      x:       { type: 'number', description: 'X coordinate to click for focus' },
      y:       { type: 'number', description: 'Y coordinate to click for focus' },
      text:    { type: 'string', description: 'Text to type' },
      submit:  { type: 'boolean', optional: true, description: 'Press Enter after typing (default false)' },
      assetId: { type: 'string', optional: true, description: 'Target tab (omit for the active tab)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./type_coordinates'),
  },
  {
    name:        'move_mouse',
    description: 'Move the mouse to coordinates without clicking. Triggers hover effects, dropdown menus, and tooltips. Shows a cursor at the position and captures a screenshot of the hover state.',
    category:    'playwright',
    schemaDef:   {
      x:       { type: 'number', description: 'X coordinate in pixels' },
      y:       { type: 'number', description: 'Y coordinate in pixels' },
      assetId: { type: 'string', optional: true, description: 'Target tab (omit for the active tab)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./move_mouse'),
  },
  {
    name:        'exec_in_page',
    description: 'Execute arbitrary JavaScript in the page context with enhanced diagnostics. Returns result, console logs, timing, DOM mutation count, navigation detection, and page state. Captures window.__sulla.__log entries (cleared before execution). Use window.__sulla.waitFor(selector) and window.__sulla.waitForIdle() helpers for post-execution synchronization. Optionally capture a screenshot after execution. Use for anything the other tools cannot do: reading DOM properties, calling widget APIs, injecting styles, triggering events, querying element positions, or interacting with third-party iframes via their JS APIs.',
    category:    'playwright',
    schemaDef:   {
      code:        { type: 'string', description: 'JavaScript code to execute in the page. The return value is sent back.' },
      screenshot:  { type: 'boolean', optional: true, description: 'Capture a screenshot after execution and include screenshotBase64 + screenshotMediaType in the response.' },
      waitFor:     { type: 'string', optional: true, description: 'CSS selector to wait for after code execution (uses window.__sulla.waitFor if available).' },
      waitForIdle: { type: 'boolean', optional: true, description: 'Wait for the page to become idle after execution (uses window.__sulla.waitForIdle if available).' },
      timeout:     { type: 'number', optional: true, default: 30000, description: 'Maximum execution timeout in milliseconds (default 30000).' },
      assetId:     { type: 'string', optional: true, description: 'Target tab (omit for the active tab)' },
    },
    operationTypes: ['execute'],
    loader:         () => import('./exec_in_page'),
  },
];
